### ISSUE TITLE
Issue-disable add button if pending method, hide existing methods from select

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#100]
Automated Review Comments
Issues in components/PublicPiggybankPage/EditPiggybankModal/EditPiggybankModal.jsx:
  - (8, 'Hardcoded string found')
  - (11, 'TODO found')
  - (11, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/EditPiggybankModal/PaymentMethodsInput.jsx:
  - (6, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (26, 'Hardcoded string found')
  - (27, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')
  - (40, 'Hardcoded string found')
  - (50, 'Line exceeds 80 characters')
  - (50, 'Hardcoded string found')
  - (52, 'Line exceeds 80 characters')
  - (53, 'Line exceeds 80 characters')
  - (55, 'Line exceeds 80 characters')
  - (65, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
  - (98, 'Hardcoded string found')
  - (102, 'Line exceeds 80 characters')
  - (103, 'Hardcoded string found')
  - (104, 'Hardcoded string found')
  - (105, 'Hardcoded string found')
  - (106, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
