### ISSUE TITLE
Issue-validate url

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#102]
Automated Review Comments
Issues in components/PublicPiggybankPage/EditPiggybankModal/EditPiggybankModal.jsx:
  - (1, 'Line exceeds 80 characters')
  - (2, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (13, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (21, 'Line exceeds 80 characters')
  - (31, 'TODO found')
  - (35, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/EditPiggybankModal/EditUrlInput.jsx:
  - (2, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
  - (29, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (75, 'Line exceeds 80 characters')
  - (77, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/EditPiggybankModal/PaymentMethodsInput.jsx:
  - (1, 'Line exceeds 80 characters')
  - (2, 'Line exceeds 80 characters')
  - (4, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
Issues in utils/hooks/useDebounce.js:
  - (2, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
