### ISSUE TITLE
Issue-cleanup. starting to work on piggybank edit update query. need to change to dot notation for firestore.

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#110]
Automated Review Comments
Issues in components/PublicPiggybankPage/EditPiggybankModal/EditPiggybankModal.jsx:
  - (3, 'Hardcoded string found')
  - (53, 'Line exceeds 80 characters')
  - (56, 'Hardcoded string found')
  - (80, 'Hardcoded string found')
  - (82, 'Line exceeds 80 characters')
  - (82, 'Hardcoded string found')
  - (83, 'Hardcoded string found')
  - (86, 'TODO found')
  - (87, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (91, 'Line exceeds 80 characters')
  - (94, 'Line exceeds 80 characters')
  - (99, 'Hardcoded string found')
  - (112, 'Hardcoded string found')
  - (129, 'Hardcoded string found')
  - (131, 'Hardcoded string found')
  - (132, 'Hardcoded string found')
  - (136, 'Hardcoded string found')
  - (137, 'Hardcoded string found')
  - (139, 'Hardcoded string found')
  - (146, 'Hardcoded string found')
  - (147, 'Hardcoded string found')
  - (158, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/EditPiggybankModal/EditUrlInput.jsx:
  - (30, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (33, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/EditPiggybankModal/PaymentMethodsInput.jsx:
  - (5, 'TODO found')
  - (5, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (18, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (54, 'Line exceeds 80 characters')
  - (57, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/EditPiggybankModal/Preview.jsx:
  - (2, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/ManagePiggybankBar/ManagePiggybankBar.jsx:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/PaymentMethodButtonModal.jsx:
  - (1, 'Line exceeds 80 characters')
  - (3, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/PublicPiggybankPage.jsx:
  - (3, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (16, 'TODO found')
  - (16, 'Line exceeds 80 characters')
  - (29, 'Hardcoded string found')
  - (32, 'TODO found')
  - (32, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (46, 'Hardcoded string found')
  - (47, 'Line exceeds 80 characters')
Issues in components/PublicPiggybankPage/util.js:
  - (5, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
Issues in components/PublicPiggybankPage/util.test.js:
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
