### ISSUE TITLE
Issue-first pass for dot-notation, buggy with payment method changes

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#114]
Automated Review Comments
Issues in components/PublicPiggybankPage/EditPiggybankModal/EditPiggybankModal.jsx:
  - (8, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (36, 'Hardcoded string found')
  - (44, 'Line exceeds 80 characters')
  - (52, 'Line exceeds 80 characters')
  - (90, 'Line exceeds 80 characters')
  - (93, 'Line exceeds 80 characters')
  - (94, 'Line exceeds 80 characters')
  - (94, 'Hardcoded string found')
  - (96, 'Line exceeds 80 characters')
  - (97, 'Line exceeds 80 characters')
  - (97, 'Hardcoded string found')
  - (98, 'Line exceeds 80 characters')
  - (101, 'Hardcoded string found')
  - (104, 'Hardcoded string found')
  - (106, 'Hardcoded string found')
  - (109, 'Hardcoded string found')
  - (115, 'Hardcoded string found')
  - (116, 'Hardcoded string found')
  - (118, 'Line exceeds 80 characters')
  - (118, 'Hardcoded string found')
  - (119, 'TODO found')
  - (119, 'Line exceeds 80 characters')
  - (119, 'Hardcoded string found')
  - (122, 'TODO found')
Issues in components/PublicPiggybankPage/EditPiggybankModal/PaymentMethodsInput.jsx:
  - (7, 'TODO found')
  - (7, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
  - (34, 'Hardcoded string found')
  - (37, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (63, 'Line exceeds 80 characters')
  - (64, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (72, 'Line exceeds 80 characters')
  - (73, 'Line exceeds 80 characters')
  - (73, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (86, 'Line exceeds 80 characters')
  - (86, 'Hardcoded string found')
  - (93, 'Hardcoded string found')
  - (98, 'Hardcoded string found')
  - (99, 'Hardcoded string found')
  - (112, 'Line exceeds 80 characters')
  - (114, 'Line exceeds 80 characters')
  - (115, 'Line exceeds 80 characters')
  - (119, 'Line exceeds 80 characters')
  - (119, 'Hardcoded string found')
  - (128, 'Line exceeds 80 characters')
  - (128, 'Hardcoded string found')
  - (130, 'Line exceeds 80 characters')
  - (131, 'Line exceeds 80 characters')
  - (134, 'Hardcoded string found')
  - (136, 'Line exceeds 80 characters')
  - (136, 'Hardcoded string found')
  - (138, 'Line exceeds 80 characters')
  - (140, 'Line exceeds 80 characters')
  - (142, 'Line exceeds 80 characters')
  - (143, 'Line exceeds 80 characters')
  - (147, 'Line exceeds 80 characters')
  - (147, 'Hardcoded string found')
  - (155, 'Hardcoded string found')
  - (157, 'Line exceeds 80 characters')
  - (157, 'Hardcoded string found')
  - (160, 'Line exceeds 80 characters')
  - (162, 'Line exceeds 80 characters')
  - (162, 'Hardcoded string found')
  - (163, 'Line exceeds 80 characters')
  - (165, 'Line exceeds 80 characters')
  - (166, 'Line exceeds 80 characters')
  - (168, 'Hardcoded string found')
  - (173, 'Line exceeds 80 characters')
  - (175, 'Line exceeds 80 characters')
  - (175, 'Hardcoded string found')
  - (176, 'Line exceeds 80 characters')
  - (190, 'Hardcoded string found')
  - (193, 'Hardcoded string found')
  - (194, 'Hardcoded string found')
  - (195, 'Hardcoded string found')
  - (200, 'Hardcoded string found')
  - (211, 'Hardcoded string found')
  - (214, 'Hardcoded string found')
  - (215, 'Hardcoded string found')
  - (216, 'Hardcoded string found')
  - (218, 'Hardcoded string found')
  - (219, 'Line exceeds 80 characters')
  - (229, 'Hardcoded string found')
  - (233, 'Line exceeds 80 characters')
  - (240, 'Hardcoded string found')
  - (241, 'Hardcoded string found')
  - (242, 'Hardcoded string found')
  - (243, 'Line exceeds 80 characters')
  - (244, 'Line exceeds 80 characters')
Issues in components/PublicPiggybankPage/EditPiggybankModal/PaymentMethodsInput.test.js:
  - (1, 'Hardcoded string found')
  - (2, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (93, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (98, 'Hardcoded string found')
  - (99, 'Hardcoded string found')
  - (103, 'Hardcoded string found')
  - (104, 'Hardcoded string found')
  - (108, 'Hardcoded string found')
  - (109, 'Hardcoded string found')
  - (113, 'Hardcoded string found')
  - (117, 'Hardcoded string found')
  - (118, 'Hardcoded string found')
  - (119, 'Hardcoded string found')
  - (120, 'Hardcoded string found')
  - (122, 'Hardcoded string found')
  - (127, 'Hardcoded string found')
  - (128, 'Hardcoded string found')
  - (129, 'Hardcoded string found')
  - (130, 'Line exceeds 80 characters')
  - (130, 'Hardcoded string found')
  - (132, 'Hardcoded string found')
  - (134, 'Line exceeds 80 characters')
  - (137, 'Hardcoded string found')
  - (138, 'Hardcoded string found')
  - (139, 'Hardcoded string found')
  - (140, 'Hardcoded string found')
  - (142, 'Hardcoded string found')
  - (143, 'Hardcoded string found')
  - (147, 'Hardcoded string found')
  - (148, 'Hardcoded string found')
  - (149, 'Hardcoded string found')
  - (150, 'Hardcoded string found')
  - (152, 'Hardcoded string found')
  - (153, 'Hardcoded string found')
  - (157, 'Hardcoded string found')
  - (158, 'Hardcoded string found')
  - (159, 'Hardcoded string found')
  - (160, 'Hardcoded string found')
  - (162, 'Hardcoded string found')
  - (169, 'Hardcoded string found')
  - (170, 'Hardcoded string found')
  - (171, 'Hardcoded string found')
  - (172, 'Line exceeds 80 characters')
  - (172, 'Hardcoded string found')
  - (174, 'Hardcoded string found')
  - (176, 'Line exceeds 80 characters')
  - (179, 'Hardcoded string found')
  - (180, 'Hardcoded string found')
  - (181, 'Hardcoded string found')
  - (182, 'Hardcoded string found')
  - (184, 'Hardcoded string found')
  - (189, 'Hardcoded string found')
  - (190, 'Hardcoded string found')
  - (191, 'Hardcoded string found')
  - (192, 'Hardcoded string found')
  - (194, 'Hardcoded string found')
  - (195, 'Hardcoded string found')
  - (199, 'Hardcoded string found')
  - (200, 'Hardcoded string found')
  - (201, 'Hardcoded string found')
  - (202, 'Hardcoded string found')
  - (204, 'Hardcoded string found')
  - (205, 'Hardcoded string found')
  - (209, 'Hardcoded string found')
  - (210, 'Hardcoded string found')
  - (211, 'Hardcoded string found')
  - (212, 'Hardcoded string found')
  - (214, 'Hardcoded string found')
  - (220, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/EditPiggybankModal/util.js:
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
Issues in components/PublicPiggybankPage/PublicPiggybankPage.jsx:
  - (5, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (18, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (37, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')
  - (69, 'Line exceeds 80 characters')
  - (69, 'Hardcoded string found')
  - (70, 'Line exceeds 80 characters')
  - (75, 'Line exceeds 80 characters')
  - (75, 'Hardcoded string found')
  - (76, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
