### ISSUE TITLE
Issue-fix bug with payment method inputs

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#116]
Automated Review Comments
Issues in components/PublicPiggybankPage/EditPiggybankModal/EditPiggybankModal.jsx:
  - (5, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (11, 'TODO found')
  - (11, 'Line exceeds 80 characters')
  - (11, 'Hardcoded string found')
  - (14, 'TODO found')
  - (15, 'TODO found')
  - (16, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
Issues in components/PublicPiggybankPage/EditPiggybankModal/PaymentMethodsInput.jsx:
  - (3, 'Hardcoded string found')
  - (9, 'TODO found')
  - (9, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Line exceeds 80 characters')
  - (27, 'TODO found')
  - (27, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (30, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
  - (34, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (36, 'Hardcoded string found')
  - (43, 'Line exceeds 80 characters')
  - (50, 'Hardcoded string found')
  - (52, 'Line exceeds 80 characters')
  - (52, 'Hardcoded string found')
  - (54, 'Line exceeds 80 characters')
  - (54, 'Hardcoded string found')
  - (57, 'Line exceeds 80 characters')
  - (58, 'Line exceeds 80 characters')
  - (60, 'Line exceeds 80 characters')
  - (62, 'Line exceeds 80 characters')
  - (63, 'Line exceeds 80 characters')
  - (64, 'Line exceeds 80 characters')
  - (68, 'Line exceeds 80 characters')
  - (68, 'Hardcoded string found')
  - (75, 'Line exceeds 80 characters')
  - (77, 'Line exceeds 80 characters')
  - (77, 'Hardcoded string found')
  - (79, 'Line exceeds 80 characters')
  - (80, 'Line exceeds 80 characters')
  - (81, 'Line exceeds 80 characters')
  - (82, 'Line exceeds 80 characters')
  - (84, 'Hardcoded string found')
  - (87, 'Line exceeds 80 characters')
  - (88, 'Line exceeds 80 characters')
  - (90, 'Line exceeds 80 characters')
  - (90, 'Hardcoded string found')
  - (91, 'Line exceeds 80 characters')
  - (93, 'Line exceeds 80 characters')
  - (97, 'Line exceeds 80 characters')
  - (108, 'Hardcoded string found')
  - (109, 'Hardcoded string found')
  - (110, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
