### ISSUE TITLE
Issue-change color + position of preferred checkbox

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#118]
Automated Review Comments
Issues in components/PublicPiggybankPage/EditPiggybankModal/PaymentMethodsInput.jsx:
  - (1, 'Line exceeds 80 characters')
  - (3, 'Line exceeds 80 characters')
  - (4, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
