### ISSUE TITLE
Issue-fix alignment of create piggybank cancel. change homepage tagline. fix piggybank delete

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#120]
Automated Review Comments
Issues in components/CreatePiggybankInput/CreatePiggybankInput.jsx:
  - (1, 'Line exceeds 80 characters')
  - (22, 'Hardcoded string found')
Issues in components/Dashboard/UserOwnedPiggybanks/AddPiggybankListItem/AddPiggybankListItem.jsx:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
Issues in components/LandingPage/LandingPage.jsx:
  - (2, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
