### ISSUE TITLE
Issue-bug fixes and cosmetic updates

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#122]
Automated Review Comments
Issues in components/LandingPage/LandingPage.jsx:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
Issues in components/PublicPiggybankPage/EditPiggybankModal/EditPiggybankModal.jsx:
  - (1, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (16, 'TODO found')
  - (17, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
  - (22, 'Hardcoded string found')
  - (24, 'Line exceeds 80 characters')
Issues in components/PublicPiggybankPage/EditPiggybankModal/PaymentMethodsInput.jsx:
  - (3, 'Hardcoded string found')
  - (14, 'TODO found')
  - (14, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
  - (29, 'TODO found')
  - (29, 'Line exceeds 80 characters')
  - (30, 'TODO found')
  - (30, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (33, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (41, 'Line exceeds 80 characters')
  - (43, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
  - (50, 'Line exceeds 80 characters')
  - (51, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (54, 'Line exceeds 80 characters')
  - (55, 'Line exceeds 80 characters')
Issues in components/PublicPiggybankPage/EditPiggybankModal/PaymentMethodsInput.test.js:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/EditPiggybankModal/util.js:
  - (10, 'Line exceeds 80 characters')
  - (25, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/EditPiggybankModal/util.test.js:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (34, 'Line exceeds 80 characters')
Issues in components/PublicPiggybankPage/PublicPiggybankPage.jsx:
  - (4, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
Issues in src/paymentMethods.jsx:
  - (1, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
