### ISSUE TITLE
Issue-fix cancel button on CreatePiggybankInput

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#124]
Automated Review Comments
Issues in components/CreatePiggybankInput/CreatePiggybankInput.jsx:
  - (1, 'Line exceeds 80 characters')
  - (30, 'Hardcoded string found')
Issues in components/Dashboard/UserOwnedPiggybanks/AddPiggybankListItem/AddPiggybankListItem.jsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/EditPiggybankModal/EditPiggybankModal.jsx:
  - (1, 'Line exceeds 80 characters')
  - (10, 'TODO found')
  - (10, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (13, 'TODO found')
  - (14, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (22, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
