### ISSUE TITLE
Issue-working on edit form submit. alphabetize public list of payment methods.

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#126]
Automated Review Comments
Issues in components/LandingPage/LandingPage.jsx:
  - (2, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
Issues in components/PublicPiggybankPage/EditPiggybankModal/EditPiggybankModal.jsx:
  - (1, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
  - (13, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (17, 'Hardcoded string found')
  - (18, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
  - (25, 'TODO found')
  - (25, 'Line exceeds 80 characters')
  - (25, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (32, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')
  - (40, 'Line exceeds 80 characters')
  - (43, 'Hardcoded string found')
  - (45, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
  - (46, 'Hardcoded string found')
  - (48, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (49, 'Hardcoded string found')
  - (51, 'TODO found')
  - (51, 'Line exceeds 80 characters')
  - (58, 'TODO found')
Issues in components/PublicPiggybankPage/EditPiggybankModal/PaymentMethodsInput.jsx:
  - (1, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/PublicPiggybankPage.jsx:
  - (8, 'TODO found')
  - (9, 'TODO found')
  - (10, 'TODO found')
  - (15, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
Issues in components/PublicPiggybankPage/util.js:
  - (4, 'Line exceeds 80 characters')
Issues in components/PublicPiggybankPage/util.test.js:
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
Issues in pages/api/createPiggybank.js:
  - (7, 'TODO found')

**Comment by satokihanada** [comment]
I got it.
