### ISSUE TITLE
Issue-lots of changes... broken form after change & re-edit

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#128]
Automated Review Comments
Issues in components/Buttons/CopyLinkShareButton.jsx:
  - (10, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
Issues in components/Dashboard/UserOwnedPiggybanks/PiggybankListItem.jsx:
  - (4, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
Issues in components/Dashboard/UserOwnedPiggybanks/PiggybankListItem/DeleteButton.jsx:
  - (11, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
Issues in components/LandingPage/LandingPage.jsx:
  - (2, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
Issues in components/PublicPiggybankPage/EditPiggybankModal/EditPiggybankModal.jsx:
  - (3, 'Line exceeds 80 characters')
  - (4, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (11, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (30, 'TODO found')
  - (30, 'Line exceeds 80 characters')
  - (30, 'Hardcoded string found')
  - (31, 'TODO found')
  - (31, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (38, 'Line exceeds 80 characters')
  - (42, 'Hardcoded string found')
  - (44, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
  - (45, 'Hardcoded string found')
  - (46, 'TODO found')
  - (46, 'Line exceeds 80 characters')
  - (46, 'Hardcoded string found')
  - (48, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (49, 'Hardcoded string found')
  - (58, 'TODO found')
  - (64, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (82, 'TODO found')
  - (82, 'Line exceeds 80 characters')
  - (82, 'Hardcoded string found')
  - (83, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/EditPiggybankModal/PaymentMethodsInput.jsx:
  - (1, 'Line exceeds 80 characters')
  - (4, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/ManagePiggybankBar/ManagePiggybankBar.jsx:
  - (4, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
Issues in components/PublicPiggybankPage/PaymentMethodButtonModal.jsx:
  - (1, 'Line exceeds 80 characters')
  - (3, 'Line exceeds 80 characters')
Issues in components/PublicPiggybankPage/PublicPiggybankPage.jsx:
  - (2, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (13, 'TODO found')
  - (14, 'TODO found')
  - (15, 'TODO found')
  - (18, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (42, 'Line exceeds 80 characters')
  - (43, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
