### ISSUE TITLE
Issue-fix modal remount issue, other minor cosmetics

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#130]
Automated Review Comments
Issues in components/Dashboard/UserOwnedPiggybanks/PiggybankListItem.jsx:
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
  - (27, 'Hardcoded string found')
Issues in components/Dashboard/UserOwnedPiggybanks/UserOwnedPiggybanks.jsx:
  - (3, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (48, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/EditPiggybankModal/EditPiggybankModal.jsx:
  - (1, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (11, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (34, 'TODO found')
  - (38, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/ManagePiggybankBar/ManagePiggybankBar.jsx:
  - (4, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
