### ISSUE TITLE
Issue-use isDirty to set update submit isDisabled

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#134]
Automated Review Comments
Issues in components/PublicPiggybankPage/EditPiggybankModal/EditPiggybankModal.jsx:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (32, 'Hardcoded string found')
  - (37, 'TODO found')
  - (37, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (51, 'Line exceeds 80 characters')
  - (54, 'Hardcoded string found')
  - (56, 'TODO found')
  - (56, 'Line exceeds 80 characters')
  - (56, 'Hardcoded string found')
  - (57, 'Line exceeds 80 characters')
  - (57, 'Hardcoded string found')
  - (60, 'Line exceeds 80 characters')
  - (60, 'Hardcoded string found')
  - (71, 'Line exceeds 80 characters')
  - (85, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
Issues in pages/api/createPiggybank.js:
  - (5, 'TODO found')
  - (5, 'Line exceeds 80 characters')
Issues in src/db/config/firestore.rules:
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
