### ISSUE TITLE
Issue-basic login w dashboard working

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#14]
Automated Review Comments
Issues in components/Dashboard/Dashboard.jsx:
  - (2, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
Issues in components/FirebaseAuth.js:
  - (10, 'Hardcoded string found')
  - (18, 'Line exceeds 80 characters')
  - (24, 'Hardcoded string found')
Issues in components/Icons/CustomIcons.jsx:
  - (4, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (18, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
Issues in components/LandingPage/LandingPage.jsx:
  - (2, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (24, 'Hardcoded string found')
Issues in pages/index.js:
  - (10, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
