### ISSUE TITLE
Issue-add underline link to piggybank list item

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#140]
Automated Review Comments
Issues in components/Dashboard/UserOwnedPiggybanks/PiggybankListItem.jsx:
  - (15, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
  - (24, 'Line exceeds 80 characters')
  - (30, 'Hardcoded string found')
Issues in components/Dashboard/UserOwnedPiggybanks/UserOwnedPiggybanks.jsx:
  - (3, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
