### ISSUE TITLE
Issue-menu and readme updates

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#154]
Automated Review Comments
Issues in README.md:
  - (1, 'Line exceeds 80 characters')
  - (3, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
Issues in components/Dashboard/Dashboard.jsx:
  - (2, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
Issues in components/Icons/CustomIcons.jsx:
  - (2, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
