### ISSUE TITLE
Issue-update tagline

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#158]
Automated Review Comments
Issues in README.md:
  - (6, 'Line exceeds 80 characters')
Issues in components/LandingPage/LandingPage.jsx:
  - (2, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
