### ISSUE TITLE
Issue-fix alignment

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#16]
Automated Review Comments
Issues in components/LandingPage/LandingPage.jsx:
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Line exceeds 80 characters')
  - (30, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
  - (32, 'Line exceeds 80 characters')
  - (32, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (38, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
