### ISSUE TITLE
Issue-fix bug with wrong error message displayed on public piggybank page server render

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#162]
Automated Review Comments
Issues in components/PublicPiggybankPage/PublicPiggybankPage.jsx:
  - (3, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (24, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
