### ISSUE TITLE
Issue-invite flow + fix bug on change piggybank url

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#177]
Automated Review Comments
Issues in components/LandingPage/LandingPage.jsx:
  - (14, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/EditPiggybankModal/EditPiggybankModal.jsx:
  - (2, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (4, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (12, 'TODO found')
  - (12, 'Line exceeds 80 characters')
Issues in components/PublicPiggybankPage/EditPiggybankModal/PaymentMethodsInput.jsx:
  - (1, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
Issues in pages/api/createPiggybank.js:
  - (2, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
Issues in server/middleware/requireBetaInvite.js:
  - (7, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
Issues in utils/hooks/useCreatePiggybank.js:
  - (1, 'Line exceeds 80 characters')
  - (4, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
