### ISSUE TITLE
Issue-add github icon, add Add tag to coins

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#18]
Automated Review Comments
Issues in LICENSE:
  - (45, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (83, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
  - (93, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
  - (104, 'Hardcoded string found')
  - (115, 'Hardcoded string found')
  - (116, 'Hardcoded string found')
  - (119, 'Hardcoded string found')
  - (124, 'Hardcoded string found')
  - (130, 'Hardcoded string found')
  - (135, 'Hardcoded string found')
  - (221, 'Hardcoded string found')
  - (240, 'Hardcoded string found')
  - (298, 'Hardcoded string found')
  - (303, 'Hardcoded string found')
  - (311, 'Hardcoded string found')
  - (346, 'Hardcoded string found')
  - (454, 'Hardcoded string found')
  - (474, 'Hardcoded string found')
  - (476, 'Hardcoded string found')
  - (478, 'Hardcoded string found')
  - (484, 'Hardcoded string found')
  - (493, 'Hardcoded string found')
  - (496, 'Hardcoded string found')
  - (508, 'Hardcoded string found')
  - (522, 'Hardcoded string found')
  - (573, 'Hardcoded string found')
  - (594, 'Hardcoded string found')
  - (633, 'Hardcoded string found')
  - (663, 'Hardcoded string found')
  - (666, 'Hardcoded string found')
Issues in components/Dashboard/Dashboard.jsx:
  - (2, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
Issues in components/Icons/CustomIcons.jsx:
  - (3, 'Line exceeds 80 characters')
  - (3, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
Issues in components/LandingPage/LandingPage.jsx:
  - (2, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (49, 'Line exceeds 80 characters')
  - (49, 'Hardcoded string found')
  - (50, 'Line exceeds 80 characters')
  - (50, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (74, 'Line exceeds 80 characters')
  - (74, 'Hardcoded string found')
  - (75, 'Line exceeds 80 characters')
  - (75, 'Hardcoded string found')
  - (76, 'Line exceeds 80 characters')
  - (76, 'Hardcoded string found')
  - (82, 'Line exceeds 80 characters')
  - (82, 'Hardcoded string found')
  - (83, 'Line exceeds 80 characters')
  - (83, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (90, 'Line exceeds 80 characters')
Issues in package.json:
  - (2, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in pages/index.js:
  - (9, 'Hardcoded string found')
Issues in yarn.lock:
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
