### ISSUE TITLE
Issue-add payment method request github template

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#201]
Automated Review Comments
Issues in components/LandingPage/LandingPage.jsx:
  - (7, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
