### ISSUE TITLE
Issue-need to enable clipboards

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#231]
Automated Review Comments
Issues in components/Icons/CustomIcons.jsx:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
  - (11, 'Line exceeds 80 characters')
  - (11, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (13, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
Issues in credits.txt:
  - (2, 'Line exceeds 80 characters')
  - (4, 'Line exceeds 80 characters')
  - (4, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
