### ISSUE TITLE
Issue-green share button only if piggybank is configured

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#243]
Automated Review Comments
Issues in components/PublicPiggybankPage/ManagePiggybankBar/ManagePiggybankBar.jsx:
  - (7, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/ManagePiggybankBar/ShareButtonModal/ShareButtonModal.jsx:
  - (2, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/PublicPiggybankPage.jsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
