### ISSUE TITLE
Issue-add no-piggybanks message to dashboard

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#253]
Automated Review Comments
Issues in components/Dashboard/Dashboard.jsx:
  - (2, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
Issues in components/Dashboard/UserOwnedPiggybanks/PiggybankListItem.jsx:
  - (2, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (11, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
Issues in components/Dashboard/UserOwnedPiggybanks/UserOwnedPiggybanks.jsx:
  - (3, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (39, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
