### ISSUE TITLE
Issue-add hamburger menu

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#259]
Automated Review Comments
Issues in README.md:
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
Issues in components/Dashboard/Dashboard.jsx:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
Issues in components/LandingPage/LandingPage.jsx:
  - (4, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
Issues in src/paymentMethods.jsx:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (26, 'Line exceeds 80 characters')
  - (30, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (35, 'Line exceeds 80 characters')
  - (39, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (71, 'Line exceeds 80 characters')
  - (75, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (81, 'Line exceeds 80 characters')
  - (84, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (90, 'Line exceeds 80 characters')
  - (93, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (96, 'Hardcoded string found')
  - (98, 'Line exceeds 80 characters')
  - (102, 'Hardcoded string found')
  - (103, 'Hardcoded string found')
  - (105, 'Hardcoded string found')
  - (108, 'Line exceeds 80 characters')
  - (108, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
