### ISSUE TITLE
Issue-merge master

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#267]
Automated Review Comments
Issues in components/Dashboard/Dashboard.jsx:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
Issues in components/Dashboard/UserOwnedPiggybanks/PiggybankListItem.jsx:
  - (2, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
