### ISSUE TITLE
Issue-add qr code

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#271]
Automated Review Comments
Issues in components/PublicPiggybankPage/PaymentMethodButtonModal.jsx:
  - (2, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (12, 'TODO found')
  - (17, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
Issues in next.config.js:
  - (5, 'Hardcoded string found')
Issues in package.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
Issues in yarn.lock:
  - (2, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (43, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (53, 'Line exceeds 80 characters')
  - (60, 'Line exceeds 80 characters')
  - (61, 'Line exceeds 80 characters')
  - (70, 'Line exceeds 80 characters')
  - (72, 'Line exceeds 80 characters')
  - (73, 'Line exceeds 80 characters')
  - (77, 'Line exceeds 80 characters')
  - (78, 'Line exceeds 80 characters')
  - (93, 'Line exceeds 80 characters')
  - (95, 'Line exceeds 80 characters')
  - (100, 'Line exceeds 80 characters')
  - (101, 'Line exceeds 80 characters')
  - (105, 'Line exceeds 80 characters')
  - (113, 'Line exceeds 80 characters')
  - (114, 'Line exceeds 80 characters')
  - (116, 'Line exceeds 80 characters')
  - (117, 'Line exceeds 80 characters')
  - (121, 'Line exceeds 80 characters')
  - (122, 'Line exceeds 80 characters')
  - (126, 'Line exceeds 80 characters')
  - (134, 'Line exceeds 80 characters')
  - (135, 'Line exceeds 80 characters')
  - (137, 'Line exceeds 80 characters')
  - (142, 'Line exceeds 80 characters')
  - (143, 'Line exceeds 80 characters')
  - (149, 'Line exceeds 80 characters')
  - (150, 'Line exceeds 80 characters')
  - (152, 'Line exceeds 80 characters')
  - (154, 'Line exceeds 80 characters')
  - (156, 'Line exceeds 80 characters')
  - (161, 'Line exceeds 80 characters')
  - (166, 'Line exceeds 80 characters')
  - (167, 'Line exceeds 80 characters')
  - (171, 'Line exceeds 80 characters')
  - (173, 'Line exceeds 80 characters')
  - (174, 'Line exceeds 80 characters')
  - (178, 'Line exceeds 80 characters')
  - (179, 'Line exceeds 80 characters')
  - (185, 'Line exceeds 80 characters')
  - (186, 'Line exceeds 80 characters')
  - (192, 'Line exceeds 80 characters')
  - (193, 'Line exceeds 80 characters')
  - (199, 'Line exceeds 80 characters')
  - (201, 'Line exceeds 80 characters')
  - (206, 'Line exceeds 80 characters')
  - (211, 'Line exceeds 80 characters')
  - (218, 'Line exceeds 80 characters')
  - (223, 'Line exceeds 80 characters')
  - (230, 'Line exceeds 80 characters')
  - (231, 'Line exceeds 80 characters')
  - (235, 'Line exceeds 80 characters')
  - (242, 'Line exceeds 80 characters')
  - (247, 'Line exceeds 80 characters')
  - (248, 'Line exceeds 80 characters')
  - (252, 'Line exceeds 80 characters')
  - (254, 'Hardcoded string found')
  - (259, 'Line exceeds 80 characters')
  - (264, 'Line exceeds 80 characters')
  - (266, 'Line exceeds 80 characters')
  - (267, 'Line exceeds 80 characters')
  - (271, 'Line exceeds 80 characters')
  - (276, 'Line exceeds 80 characters')
  - (278, 'Line exceeds 80 characters')
  - (279, 'Line exceeds 80 characters')
  - (283, 'Line exceeds 80 characters')
  - (288, 'Line exceeds 80 characters')
  - (295, 'Line exceeds 80 characters')
  - (296, 'Line exceeds 80 characters')
  - (331, 'Line exceeds 80 characters')
  - (333, 'Line exceeds 80 characters')
  - (334, 'Line exceeds 80 characters')
  - (338, 'Line exceeds 80 characters')
  - (339, 'Line exceeds 80 characters')
  - (343, 'Line exceeds 80 characters')
  - (350, 'Line exceeds 80 characters')
  - (351, 'Line exceeds 80 characters')
  - (363, 'Line exceeds 80 characters')
  - (370, 'Line exceeds 80 characters')
  - (375, 'Line exceeds 80 characters')
  - (382, 'Line exceeds 80 characters')
  - (387, 'Line exceeds 80 characters')
  - (394, 'Line exceeds 80 characters')
  - (395, 'Line exceeds 80 characters')
  - (402, 'Line exceeds 80 characters')
  - (409, 'Line exceeds 80 characters')
  - (410, 'Line exceeds 80 characters')
  - (414, 'Line exceeds 80 characters')
  - (421, 'Line exceeds 80 characters')
  - (422, 'Line exceeds 80 characters')
  - (432, 'Line exceeds 80 characters')
  - (433, 'Line exceeds 80 characters')
  - (443, 'Line exceeds 80 characters')
  - (448, 'Line exceeds 80 characters')
  - (449, 'Line exceeds 80 characters')
  - (451, 'Line exceeds 80 characters')
  - (452, 'Line exceeds 80 characters')
  - (454, 'Line exceeds 80 characters')
  - (459, 'Line exceeds 80 characters')
  - (460, 'Line exceeds 80 characters')
  - (464, 'Line exceeds 80 characters')
  - (471, 'Line exceeds 80 characters')
  - (476, 'Line exceeds 80 characters')
  - (483, 'Line exceeds 80 characters')
  - (488, 'Line exceeds 80 characters')
  - (490, 'Line exceeds 80 characters')
  - (491, 'Line exceeds 80 characters')
  - (495, 'Line exceeds 80 characters')
  - (500, 'Line exceeds 80 characters')
  - (502, 'Line exceeds 80 characters')
  - (503, 'Line exceeds 80 characters')
  - (508, 'Line exceeds 80 characters')
  - (509, 'Line exceeds 80 characters')
  - (515, 'Line exceeds 80 characters')
  - (516, 'Line exceeds 80 characters')
  - (520, 'Line exceeds 80 characters')
  - (522, 'Line exceeds 80 characters')
  - (527, 'Line exceeds 80 characters')
  - (528, 'Line exceeds 80 characters')
  - (532, 'Line exceeds 80 characters')
  - (534, 'Line exceeds 80 characters')
  - (539, 'Line exceeds 80 characters')
  - (540, 'Line exceeds 80 characters')
  - (544, 'Line exceeds 80 characters')
  - (551, 'Line exceeds 80 characters')
  - (558, 'Line exceeds 80 characters')
  - (565, 'Line exceeds 80 characters')
  - (566, 'Line exceeds 80 characters')
  - (570, 'Line exceeds 80 characters')
  - (572, 'Line exceeds 80 characters')
  - (573, 'Line exceeds 80 characters')
  - (577, 'Line exceeds 80 characters')
  - (578, 'Line exceeds 80 characters')
  - (582, 'Line exceeds 80 characters')
  - (584, 'Line exceeds 80 characters')
  - (585, 'Line exceeds 80 characters')
  - (589, 'Line exceeds 80 characters')
  - (594, 'Line exceeds 80 characters')
  - (599, 'Line exceeds 80 characters')
  - (600, 'Line exceeds 80 characters')
  - (602, 'Line exceeds 80 characters')
  - (603, 'Line exceeds 80 characters')
  - (605, 'Hardcoded string found')
  - (610, 'Line exceeds 80 characters')
  - (611, 'Line exceeds 80 characters')
  - (618, 'Line exceeds 80 characters')
  - (620, 'Line exceeds 80 characters')
  - (621, 'Line exceeds 80 characters')
  - (625, 'Line exceeds 80 characters')
  - (630, 'Line exceeds 80 characters')
  - (631, 'Line exceeds 80 characters')
  - (639, 'Line exceeds 80 characters')
  - (640, 'Line exceeds 80 characters')
  - (644, 'Line exceeds 80 characters')
  - (651, 'Line exceeds 80 characters')
  - (652, 'Line exceeds 80 characters')
  - (656, 'Line exceeds 80 characters')
  - (657, 'Line exceeds 80 characters')
  - (666, 'Line exceeds 80 characters')
  - (673, 'Line exceeds 80 characters')
  - (674, 'Line exceeds 80 characters')
  - (676, 'Line exceeds 80 characters')
  - (678, 'Line exceeds 80 characters')
  - (679, 'Line exceeds 80 characters')
  - (683, 'Line exceeds 80 characters')
  - (684, 'Line exceeds 80 characters')
  - (688, 'Line exceeds 80 characters')
  - (690, 'Line exceeds 80 characters')
  - (691, 'Line exceeds 80 characters')
  - (695, 'Line exceeds 80 characters')
  - (696, 'Line exceeds 80 characters')
  - (714, 'Line exceeds 80 characters')
  - (715, 'Line exceeds 80 characters')
  - (721, 'Line exceeds 80 characters')
  - (722, 'Line exceeds 80 characters')
  - (731, 'Line exceeds 80 characters')
  - (733, 'Line exceeds 80 characters')
  - (738, 'Line exceeds 80 characters')
  - (739, 'Line exceeds 80 characters')
  - (743, 'Line exceeds 80 characters')
  - (750, 'Line exceeds 80 characters')
  - (755, 'Line exceeds 80 characters')
  - (757, 'Line exceeds 80 characters')
  - (762, 'Line exceeds 80 characters')
  - (763, 'Line exceeds 80 characters')
  - (767, 'Line exceeds 80 characters')
  - (769, 'Line exceeds 80 characters')
  - (770, 'Line exceeds 80 characters')
  - (774, 'Line exceeds 80 characters')
  - (775, 'Line exceeds 80 characters')
  - (779, 'Line exceeds 80 characters')
  - (781, 'Line exceeds 80 characters')
  - (782, 'Line exceeds 80 characters')
  - (786, 'Line exceeds 80 characters')
  - (787, 'Line exceeds 80 characters')
  - (794, 'Line exceeds 80 characters')
  - (801, 'Line exceeds 80 characters')
  - (806, 'Line exceeds 80 characters')
  - (813, 'Line exceeds 80 characters')
  - (818, 'Line exceeds 80 characters')
  - (825, 'Line exceeds 80 characters')
  - (830, 'Line exceeds 80 characters')
  - (832, 'Line exceeds 80 characters')
  - (833, 'Line exceeds 80 characters')
  - (837, 'Line exceeds 80 characters')
  - (838, 'Line exceeds 80 characters')
  - (856, 'Line exceeds 80 characters')
  - (863, 'Line exceeds 80 characters')
  - (864, 'Line exceeds 80 characters')
  - (870, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
