### ISSUE TITLE
Issue-Landing page use cases (#38)

* wip [skip ci]

* wip [skip ci]

* wip [skip ci]

* wip [skip ci]

* wip [skip ci]

* wip [skip ci]

* wip [skip ci]

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#299]
Automated Review Comments
Issues in .env.local.example:
  - (2, 'Line exceeds 80 characters')
Issues in README.md:
  - (1, 'Line exceeds 80 characters')
  - (4, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
Issues in components/Icons/CustomIcons.jsx:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (29, 'Hardcoded string found')
Issues in components/LandingPage/FAQ.jsx:
  - (26, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
  - (64, 'Line exceeds 80 characters')
  - (71, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
Issues in components/LandingPage/LandingPage.jsx:
  - (1, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (54, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (68, 'Line exceeds 80 characters')
  - (76, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (95, 'Hardcoded string found')
  - (98, 'Hardcoded string found')
  - (99, 'Hardcoded string found')
  - (102, 'Hardcoded string found')
  - (107, 'Hardcoded string found')
  - (110, 'Hardcoded string found')
  - (111, 'Line exceeds 80 characters')
  - (112, 'Hardcoded string found')
  - (121, 'Hardcoded string found')
  - (125, 'Hardcoded string found')
  - (128, 'Hardcoded string found')
  - (129, 'Hardcoded string found')
  - (136, 'Hardcoded string found')
  - (139, 'Hardcoded string found')
  - (147, 'Hardcoded string found')
  - (151, 'Hardcoded string found')
  - (152, 'Hardcoded string found')
  - (169, 'Hardcoded string found')
  - (171, 'Hardcoded string found')
  - (175, 'Hardcoded string found')
  - (179, 'Hardcoded string found')
  - (182, 'Hardcoded string found')
  - (183, 'Hardcoded string found')
  - (186, 'Hardcoded string found')
  - (187, 'Line exceeds 80 characters')
  - (191, 'Hardcoded string found')
  - (193, 'Line exceeds 80 characters')
  - (198, 'Hardcoded string found')
  - (202, 'Hardcoded string found')
  - (206, 'Hardcoded string found')
  - (211, 'Line exceeds 80 characters')
  - (219, 'Line exceeds 80 characters')
  - (220, 'Line exceeds 80 characters')
  - (221, 'Line exceeds 80 characters')
  - (233, 'Line exceeds 80 characters')
  - (251, 'Hardcoded string found')
  - (255, 'Hardcoded string found')
  - (258, 'Hardcoded string found')
  - (261, 'Hardcoded string found')
Issues in components/LandingPage/UseCasesList.jsx:
  - (3, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
Issues in package.json:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in src/settings.js:
  - (4, 'TODO found')
  - (4, 'Line exceeds 80 characters')
Issues in yarn.lock:
  - (8, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
