### ISSUE TITLE
Issue-adding dynamic import

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#303]
Automated Review Comments
Issues in components/LandingPage/LandingPage.jsx:
  - (4, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
Issues in components/LandingPage/Typewriter.jsx:
  - (2, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (26, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
