### ISSUE TITLE
Issue-disable typewriter ssr

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#307]
Automated Review Comments
Issues in components/LandingPage/Typewriter.jsx:
  - (2, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (49, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
