### ISSUE TITLE
Issue-remove AddTag from landing page, replace it with a FAQ

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#309]
Automated Review Comments
Issues in components/LandingPage/FAQ.jsx:
  - (8, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
Issues in components/LandingPage/LandingPage.jsx:
  - (7, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (11, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
Issues in components/LandingPage/Typewriter.jsx:
  - (2, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
