### ISSUE TITLE
Issue-fix some lightsail issues

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#320]
Automated Review Comments
Issues in components/CreatePiggybankInput/CreatePiggybankInput.jsx:
  - (1, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
Issues in components/Dashboard/Dashboard.jsx:
  - (3, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (11, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
Issues in components/LandingPage/FAQ.jsx:
  - (3, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
Issues in components/LandingPage/LandingPage.jsx:
  - (4, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (22, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
Issues in components/logo/Logo.jsx:
  - (5, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
