### ISSUE TITLE
Issue-new favicon (#42)

* wip [skip ci]

* wip [skip ci]

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#330]
Automated Review Comments
Issues in components/LandingPage/FAQ.jsx:
  - (1, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
Issues in pages/_document.jsx:
  - (3, 'Line exceeds 80 characters')
  - (3, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (4, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
Issues in public/favicon/safari-pinned-tab.svg:
  - (2, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
Issues in public/site.webmanifest:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (20, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
