### ISSUE TITLE
Issue-unify logo (#44)

* working but embed button doesnt have question mark

* wip [skip ci]

* clean up qr code, unrelated but quick

* wip [skip ci]

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#334]
Automated Review Comments
Issues in components/PublicPiggybankPage/ManagePiggybankBar/ShareButtonModal/PiggybankQRCode.jsx:
  - (9, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/ManagePiggybankBar/ShareButtonModal/ShareEmbedButton.jsx:
  - (4, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
Issues in src/embed-button/embed-button.js:
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
