### ISSUE TITLE
Issue-change tagline & other verbiage tweaks

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#338]
Automated Review Comments
Issues in components/LandingPage/FAQ.jsx:
  - (1, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (21, 'Hardcoded string found')
  - (26, 'Line exceeds 80 characters')
  - (44, 'Hardcoded string found')
  - (49, 'Line exceeds 80 characters')
Issues in components/LandingPage/LandingPage.jsx:
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (30, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')
  - (46, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
Issues in public/site.webmanifest:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
