### ISSUE TITLE
Issue-Bump next from 9.5.3 to 9.5.4

Bumps [next](https://github.com/vercel/next.js) from 9.5.3 to 9.5.4.
- [Release notes](https://github.com/vercel/next.js/releases)
- [Changelog](https://github.com/vercel/next.js/blob/canary/release.js)
- [Commits](https://github.com/vercel/next.js/compare/v9.5.3...v9.5.4)

Signed-off-by: dependabot[bot] <support@github.com>

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#340]
Automated Review Comments
Issues in package.json:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
Issues in yarn.lock:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (21, 'Hardcoded string found')
  - (26, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')
  - (43, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (51, 'Hardcoded string found')
  - (59, 'Line exceeds 80 characters')
  - (60, 'Line exceeds 80 characters')
  - (63, 'Line exceeds 80 characters')
  - (64, 'Line exceeds 80 characters')
  - (69, 'Hardcoded string found')
  - (74, 'Line exceeds 80 characters')
  - (75, 'Line exceeds 80 characters')
  - (81, 'Line exceeds 80 characters')
  - (82, 'Line exceeds 80 characters')
  - (83, 'Line exceeds 80 characters')
  - (84, 'Line exceeds 80 characters')
  - (89, 'Line exceeds 80 characters')
  - (90, 'Line exceeds 80 characters')
  - (92, 'Line exceeds 80 characters')
  - (93, 'Line exceeds 80 characters')
  - (97, 'Line exceeds 80 characters')
  - (98, 'Line exceeds 80 characters')
  - (101, 'Line exceeds 80 characters')
  - (102, 'Line exceeds 80 characters')
  - (106, 'Hardcoded string found')
  - (140, 'Line exceeds 80 characters')
  - (141, 'Line exceeds 80 characters')
  - (145, 'Line exceeds 80 characters')
  - (146, 'Line exceeds 80 characters')
  - (150, 'Line exceeds 80 characters')
  - (157, 'Line exceeds 80 characters')
  - (158, 'Line exceeds 80 characters')
  - (166, 'Line exceeds 80 characters')
  - (168, 'Line exceeds 80 characters')
  - (173, 'Line exceeds 80 characters')
  - (174, 'Line exceeds 80 characters')
  - (177, 'Line exceeds 80 characters')
  - (178, 'Line exceeds 80 characters')
  - (207, 'Line exceeds 80 characters')
  - (208, 'Line exceeds 80 characters')
  - (210, 'Line exceeds 80 characters')
  - (211, 'Line exceeds 80 characters')
  - (213, 'Line exceeds 80 characters')
  - (214, 'Line exceeds 80 characters')
  - (218, 'Line exceeds 80 characters')
  - (219, 'Line exceeds 80 characters')
  - (223, 'Line exceeds 80 characters')
  - (230, 'Line exceeds 80 characters')
  - (231, 'Line exceeds 80 characters')
  - (238, 'Line exceeds 80 characters')
  - (245, 'Line exceeds 80 characters')
  - (246, 'Line exceeds 80 characters')
  - (250, 'Line exceeds 80 characters')
  - (252, 'Line exceeds 80 characters')
  - (253, 'Line exceeds 80 characters')
  - (258, 'Line exceeds 80 characters')
  - (259, 'Line exceeds 80 characters')
  - (261, 'Line exceeds 80 characters')
  - (266, 'Line exceeds 80 characters')
  - (267, 'Line exceeds 80 characters')
  - (270, 'Line exceeds 80 characters')
  - (271, 'Line exceeds 80 characters')
  - (273, 'Hardcoded string found')
  - (274, 'Hardcoded string found')
  - (275, 'Hardcoded string found')
  - (276, 'Hardcoded string found')
  - (277, 'Hardcoded string found')
  - (278, 'Hardcoded string found')
  - (279, 'Hardcoded string found')
  - (280, 'Hardcoded string found')
  - (281, 'Hardcoded string found')
  - (282, 'Hardcoded string found')
  - (283, 'Hardcoded string found')
  - (284, 'Hardcoded string found')
  - (285, 'Hardcoded string found')
  - (286, 'Hardcoded string found')
  - (287, 'Hardcoded string found')
  - (289, 'Hardcoded string found')
  - (290, 'Hardcoded string found')
  - (291, 'Hardcoded string found')
  - (292, 'Hardcoded string found')
  - (293, 'Hardcoded string found')
  - (294, 'Hardcoded string found')
  - (295, 'Hardcoded string found')
  - (296, 'Hardcoded string found')
  - (297, 'Hardcoded string found')
  - (339, 'Line exceeds 80 characters')
  - (340, 'Line exceeds 80 characters')
  - (343, 'Line exceeds 80 characters')
  - (344, 'Line exceeds 80 characters')
  - (355, 'Line exceeds 80 characters')
  - (356, 'Line exceeds 80 characters')
  - (357, 'Line exceeds 80 characters')
  - (364, 'Line exceeds 80 characters')
  - (365, 'Line exceeds 80 characters')
  - (370, 'Line exceeds 80 characters')
  - (371, 'Line exceeds 80 characters')
  - (373, 'Line exceeds 80 characters')
  - (374, 'Line exceeds 80 characters')
  - (382, 'Line exceeds 80 characters')
  - (383, 'Line exceeds 80 characters')
  - (390, 'Line exceeds 80 characters')
  - (391, 'Line exceeds 80 characters')
  - (398, 'Line exceeds 80 characters')
  - (399, 'Line exceeds 80 characters')
  - (402, 'Line exceeds 80 characters')
  - (403, 'Line exceeds 80 characters')
  - (424, 'Line exceeds 80 characters')
  - (425, 'Line exceeds 80 characters')
  - (428, 'Line exceeds 80 characters')
  - (429, 'Line exceeds 80 characters')
  - (433, 'Hardcoded string found')
  - (445, 'Line exceeds 80 characters')
  - (446, 'Line exceeds 80 characters')
  - (448, 'Hardcoded string found')
  - (452, 'Line exceeds 80 characters')
  - (454, 'Line exceeds 80 characters')
  - (461, 'Line exceeds 80 characters')
  - (462, 'Line exceeds 80 characters')
  - (468, 'Line exceeds 80 characters')
  - (475, 'Line exceeds 80 characters')
  - (476, 'Line exceeds 80 characters')
  - (479, 'Line exceeds 80 characters')
  - (480, 'Line exceeds 80 characters')
  - (487, 'Line exceeds 80 characters')
  - (488, 'Line exceeds 80 characters')
  - (492, 'Line exceeds 80 characters')
  - (493, 'Line exceeds 80 characters')
  - (504, 'Line exceeds 80 characters')
  - (511, 'Line exceeds 80 characters')
  - (512, 'Line exceeds 80 characters')
  - (515, 'Line exceeds 80 characters')
  - (516, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
