### ISSUE TITLE
Issue-Better landing page GitHub logo (#46)

* wip [skip ci]

* wip [skip ci]

* add modern github corner

* prettify css

* wip [skip ci]

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#344]
Automated Review Comments
Issues in components/LandingPage/FAQ.jsx:
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
Issues in components/LandingPage/GithubLink.jsx:
  - (11, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (33, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')
  - (36, 'Hardcoded string found')
  - (41, 'Line exceeds 80 characters')
  - (42, 'Hardcoded string found')
Issues in components/LandingPage/LandingPage.jsx:
  - (3, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (29, 'Line exceeds 80 characters')
  - (29, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
