### ISSUE TITLE
Issue-Show piggybank utilization on dashboard (#48)

* wip [skip ci]

* wip [skip ci]

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#348]
Automated Review Comments
Issues in components/Dashboard/Dashboard.jsx:
  - (2, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (22, 'Line exceeds 80 characters')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
Issues in components/Dashboard/UserOwnedPiggybanks/AddPiggybankListItem/AddPiggybankListItem.jsx:
  - (2, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (17, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (29, 'Line exceeds 80 characters')
Issues in components/Dashboard/UserOwnedPiggybanks/PiggybankLimitUtilization.jsx:
  - (4, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (37, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')
Issues in components/Dashboard/UserOwnedPiggybanks/UserOwnedPiggybanks.jsx:
  - (3, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
Issues in src/settings.js:
  - (11, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
