### ISSUE TITLE
Issue-remove question mark from logo. use SVG where possible instead of PNG (#49)

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#350]
Automated Review Comments
Issues in components/Icons/CustomIcons.jsx:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
Issues in components/LandingPage/LandingPage.jsx:
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
Issues in components/logo/Logo.jsx:
  - (3, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
Issues in components/logo/piggybank-without-money-sign.svg:
  - (2, 'Line exceeds 80 characters')
Issues in src/next-seo.config.js:
  - (2, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (16, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
