### ISSUE TITLE
Issue-Add Privacy Policy and Terms of Service (#51)

* wip [skip ci]

* draft privacy policy and ToS

* wip [skip ci]

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#354]
Automated Review Comments
Issues in PRIVACY_POLICY.md:
  - (4, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
  - (13, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
  - (27, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
Issues in TERMS_OF_SERVICE.md:
  - (8, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
