### ISSUE TITLE
Issue-add footer (#52)

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#356]
Automated Review Comments
Issues in components/LandingPage/Footer.jsx:
  - (2, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
Issues in src/settings.js:
  - (1, 'Line exceeds 80 characters')
  - (4, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
