### ISSUE TITLE
Issue-Responsive comparison table (#53)

* looks good, but going to make code DRY

* make table DRY

* tweak table styling

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#358]
Automated Review Comments
Issues in components/LandingPage/CompetitorComparisonTable.jsx:
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (83, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (116, 'Line exceeds 80 characters')
  - (116, 'Hardcoded string found')
  - (128, 'Line exceeds 80 characters')
  - (128, 'Hardcoded string found')
  - (137, 'Hardcoded string found')
  - (138, 'Hardcoded string found')
  - (139, 'Hardcoded string found')
  - (145, 'Hardcoded string found')
  - (147, 'Line exceeds 80 characters')
  - (147, 'Hardcoded string found')
  - (157, 'Line exceeds 80 characters')
  - (177, 'Line exceeds 80 characters')
Issues in components/LandingPage/LandingPage.jsx:
  - (2, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (42, 'Line exceeds 80 characters')
  - (46, 'Hardcoded string found')
  - (48, 'Line exceeds 80 characters')
  - (48, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (66, 'Line exceeds 80 characters')
  - (74, 'Line exceeds 80 characters')
  - (75, 'Line exceeds 80 characters')
  - (76, 'Line exceeds 80 characters')
  - (88, 'Line exceeds 80 characters')
  - (105, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
