### ISSUE TITLE
Issue-improve and simplify logo responsiveness (#54)

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#360]
Automated Review Comments
Issues in components/logo/Logo.jsx:
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (58, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
