### ISSUE TITLE
Issue-specify only lowercase in create input error

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#364]
Automated Review Comments
Issues in components/CreatePiggybankInput/CreatePiggybankInput.jsx:
  - (1, 'Line exceeds 80 characters')
  - (3, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
