### ISSUE TITLE
Issue-Landing page tweaks (#55)

* wip [skip ci]

* wip [skip ci]

* wip [skip ci]

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#366]
Automated Review Comments
Issues in components/LandingPage/LandingPage.jsx:
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
Issues in components/LandingPage/UseCasesList.jsx:
  - (3, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
