### ISSUE TITLE
Issue-use customTheme correctly. fix utilization bar colors

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#370]
Automated Review Comments
Issues in components/Dashboard/UserOwnedPiggybanks/PiggybankLimitUtilization.jsx:
  - (1, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
Issues in components/logo/Logo.jsx:
  - (17, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
Issues in components/theme.js:
  - (6, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (31, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
