### ISSUE TITLE
Issue-fix icon on payment method button modal. last remaining issue in migration seems to be payment method box sizes on public piggybank page

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#372]
Automated Review Comments
Issues in components/PublicPiggybankPage/PaymentMethodButton.jsx:
  - (3, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
Issues in components/PublicPiggybankPage/PaymentMethodButtonModal.jsx:
  - (1, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
