### ISSUE TITLE
Issue-use Wrap instead of Stack for payment method buttons. For some reason v1 Chakra Stack behaves differently

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#374]
Automated Review Comments
Issues in components/PublicPiggybankPage/PublicPiggybankPage.jsx:
  - (2, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (34, 'Hardcoded string found')
  - (43, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (49, 'Hardcoded string found')
  - (55, 'Line exceeds 80 characters')
  - (55, 'Hardcoded string found')
  - (62, 'Line exceeds 80 characters')
  - (62, 'Hardcoded string found')
  - (67, 'Line exceeds 80 characters')
  - (67, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
