### ISSUE TITLE
Issue-firebase bump from 7.19.1 to 7.24.0 caused break in auth

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#381]
Automated Review Comments
Issues in package.json:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
Issues in yarn.lock:
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (36, 'Line exceeds 80 characters')
  - (37, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (42, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
  - (48, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (58, 'Line exceeds 80 characters')
  - (59, 'Line exceeds 80 characters')
  - (63, 'Line exceeds 80 characters')
  - (64, 'Line exceeds 80 characters')
  - (67, 'Line exceeds 80 characters')
  - (68, 'Line exceeds 80 characters')
  - (70, 'Hardcoded string found')
  - (74, 'Line exceeds 80 characters')
  - (75, 'Line exceeds 80 characters')
  - (77, 'Hardcoded string found')
  - (82, 'Line exceeds 80 characters')
  - (85, 'Hardcoded string found')
  - (90, 'Line exceeds 80 characters')
  - (91, 'Line exceeds 80 characters')
  - (93, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (95, 'Hardcoded string found')
  - (96, 'Hardcoded string found')
  - (97, 'Hardcoded string found')
  - (103, 'Line exceeds 80 characters')
  - (104, 'Line exceeds 80 characters')
  - (111, 'Line exceeds 80 characters')
  - (112, 'Line exceeds 80 characters')
  - (115, 'Line exceeds 80 characters')
  - (116, 'Line exceeds 80 characters')
  - (120, 'Line exceeds 80 characters')
  - (121, 'Line exceeds 80 characters')
  - (124, 'Line exceeds 80 characters')
  - (125, 'Line exceeds 80 characters')
  - (127, 'Hardcoded string found')
  - (128, 'Hardcoded string found')
  - (129, 'Hardcoded string found')
  - (130, 'Hardcoded string found')
  - (131, 'Hardcoded string found')
  - (132, 'Hardcoded string found')
  - (133, 'Hardcoded string found')
  - (134, 'Hardcoded string found')
  - (135, 'Hardcoded string found')
  - (136, 'Hardcoded string found')
  - (137, 'Hardcoded string found')
  - (144, 'Line exceeds 80 characters')
  - (145, 'Line exceeds 80 characters')
  - (149, 'Line exceeds 80 characters')
  - (150, 'Line exceeds 80 characters')
  - (153, 'Line exceeds 80 characters')
  - (154, 'Line exceeds 80 characters')
  - (156, 'Hardcoded string found')
  - (157, 'Hardcoded string found')
  - (158, 'Hardcoded string found')
  - (159, 'Hardcoded string found')
  - (166, 'Line exceeds 80 characters')
  - (167, 'Line exceeds 80 characters')
  - (171, 'Line exceeds 80 characters')
  - (172, 'Line exceeds 80 characters')
  - (175, 'Line exceeds 80 characters')
  - (176, 'Line exceeds 80 characters')
  - (178, 'Hardcoded string found')
  - (179, 'Hardcoded string found')
  - (180, 'Hardcoded string found')
  - (181, 'Hardcoded string found')
  - (182, 'Hardcoded string found')
  - (187, 'Line exceeds 80 characters')
  - (188, 'Line exceeds 80 characters')
  - (192, 'Line exceeds 80 characters')
  - (193, 'Line exceeds 80 characters')
  - (196, 'Line exceeds 80 characters')
  - (197, 'Line exceeds 80 characters')
  - (199, 'Hardcoded string found')
  - (200, 'Hardcoded string found')
  - (201, 'Hardcoded string found')
  - (202, 'Hardcoded string found')
  - (203, 'Hardcoded string found')
  - (204, 'Hardcoded string found')
  - (205, 'Hardcoded string found')
  - (210, 'Line exceeds 80 characters')
  - (211, 'Line exceeds 80 characters')
  - (215, 'Line exceeds 80 characters')
  - (216, 'Line exceeds 80 characters')
  - (219, 'Line exceeds 80 characters')
  - (220, 'Line exceeds 80 characters')
  - (222, 'Hardcoded string found')
  - (223, 'Hardcoded string found')
  - (224, 'Hardcoded string found')
  - (225, 'Hardcoded string found')
  - (226, 'Hardcoded string found')
  - (227, 'Hardcoded string found')
  - (228, 'Hardcoded string found')
  - (229, 'Hardcoded string found')
  - (234, 'Line exceeds 80 characters')
  - (235, 'Line exceeds 80 characters')
  - (239, 'Line exceeds 80 characters')
  - (240, 'Line exceeds 80 characters')
  - (243, 'Line exceeds 80 characters')
  - (244, 'Line exceeds 80 characters')
  - (246, 'Hardcoded string found')
  - (247, 'Hardcoded string found')
  - (248, 'Hardcoded string found')
  - (249, 'Hardcoded string found')
  - (250, 'Hardcoded string found')
  - (251, 'Hardcoded string found')
  - (252, 'Hardcoded string found')
  - (253, 'Hardcoded string found')
  - (258, 'Line exceeds 80 characters')
  - (259, 'Line exceeds 80 characters')
  - (263, 'Line exceeds 80 characters')
  - (264, 'Line exceeds 80 characters')
  - (267, 'Line exceeds 80 characters')
  - (268, 'Line exceeds 80 characters')
  - (270, 'Hardcoded string found')
  - (271, 'Hardcoded string found')
  - (272, 'Hardcoded string found')
  - (273, 'Hardcoded string found')
  - (274, 'Hardcoded string found')
  - (279, 'Line exceeds 80 characters')
  - (280, 'Line exceeds 80 characters')
  - (291, 'Line exceeds 80 characters')
  - (292, 'Line exceeds 80 characters')
  - (295, 'Line exceeds 80 characters')
  - (296, 'Line exceeds 80 characters')
  - (301, 'Line exceeds 80 characters')
  - (305, 'Line exceeds 80 characters')
  - (306, 'Line exceeds 80 characters')
  - (308, 'Line exceeds 80 characters')
  - (309, 'Line exceeds 80 characters')
  - (314, 'Line exceeds 80 characters')
  - (319, 'Line exceeds 80 characters')
  - (320, 'Line exceeds 80 characters')
  - (326, 'Line exceeds 80 characters')
  - (334, 'Line exceeds 80 characters')
  - (335, 'Line exceeds 80 characters')
  - (337, 'Hardcoded string found')
  - (338, 'Hardcoded string found')
  - (342, 'Line exceeds 80 characters')
  - (343, 'Line exceeds 80 characters')
  - (346, 'Line exceeds 80 characters')
  - (347, 'Line exceeds 80 characters')
  - (349, 'Hardcoded string found')
  - (350, 'Hardcoded string found')
  - (351, 'Hardcoded string found')
  - (352, 'Hardcoded string found')
  - (353, 'Hardcoded string found')
  - (354, 'Hardcoded string found')
  - (355, 'Hardcoded string found')
  - (356, 'Hardcoded string found')
  - (357, 'Hardcoded string found')
  - (358, 'Hardcoded string found')
  - (359, 'Hardcoded string found')
  - (360, 'Hardcoded string found')
  - (361, 'Hardcoded string found')
  - (362, 'Hardcoded string found')
  - (363, 'Hardcoded string found')
  - (364, 'Hardcoded string found')
  - (365, 'Hardcoded string found')
  - (366, 'Hardcoded string found')
  - (367, 'Hardcoded string found')
  - (368, 'Hardcoded string found')
  - (369, 'Hardcoded string found')
  - (370, 'Hardcoded string found')
  - (371, 'Hardcoded string found')
  - (372, 'Hardcoded string found')
  - (373, 'Hardcoded string found')
  - (374, 'Hardcoded string found')
  - (384, 'Line exceeds 80 characters')
  - (385, 'Line exceeds 80 characters')
  - (391, 'Line exceeds 80 characters')
  - (393, 'Line exceeds 80 characters')
  - (394, 'Line exceeds 80 characters')
  - (399, 'Line exceeds 80 characters')
  - (402, 'Line exceeds 80 characters')
  - (407, 'Line exceeds 80 characters')
  - (415, 'Line exceeds 80 characters')
  - (417, 'Line exceeds 80 characters')
  - (418, 'Line exceeds 80 characters')
  - (422, 'Line exceeds 80 characters')
  - (423, 'Line exceeds 80 characters')
  - (430, 'Line exceeds 80 characters')
  - (435, 'Line exceeds 80 characters')
  - (436, 'Line exceeds 80 characters')
  - (438, 'Line exceeds 80 characters')
  - (439, 'Line exceeds 80 characters')
  - (441, 'Line exceeds 80 characters')
  - (442, 'Line exceeds 80 characters')
  - (446, 'Line exceeds 80 characters')
  - (447, 'Line exceeds 80 characters')
  - (451, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
