### ISSUE TITLE
Issue-fix console warnings

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#385]
Automated Review Comments
Issues in components/LandingPage/CompetitorComparisonTable.jsx:
  - (6, 'Line exceeds 80 characters')
  - (11, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (44, 'Line exceeds 80 characters')
  - (44, 'Hardcoded string found')
  - (56, 'Line exceeds 80 characters')
  - (56, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (95, 'Line exceeds 80 characters')
  - (98, 'Line exceeds 80 characters')
  - (106, 'Line exceeds 80 characters')
  - (114, 'Line exceeds 80 characters')
  - (114, 'Hardcoded string found')
  - (127, 'Line exceeds 80 characters')
  - (130, 'Line exceeds 80 characters')
  - (130, 'Hardcoded string found')
  - (141, 'Hardcoded string found')
  - (142, 'Hardcoded string found')
  - (143, 'Hardcoded string found')
  - (150, 'Hardcoded string found')
  - (164, 'Line exceeds 80 characters')
  - (169, 'Line exceeds 80 characters')
  - (184, 'Line exceeds 80 characters')
Issues in components/LandingPage/GithubLink.jsx:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in components/LandingPage/LandingPage.jsx:
  - (2, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
Issues in components/LandingPage/PaymentMethodTag.jsx:
  - (3, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
Issues in pages/_document.jsx:
  - (2, 'Line exceeds 80 characters')
  - (3, 'Line exceeds 80 characters')
  - (3, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
