### ISSUE TITLE
Issue-fix all lint errors and warnings

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#397]
Automated Review Comments
Issues in .eslintrc:
  - (2, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
Issues in components/Auth/AuthModal.jsx:
  - (4, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
Issues in components/CreatePiggybankInput/CreatePiggybankInput.jsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
Issues in components/Dashboard/Dashboard.jsx:
  - (2, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
Issues in components/Dashboard/UserOwnedPiggybanks/AddPiggybankListItem/AddPiggybankListItem.jsx:
  - (2, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
Issues in components/Dashboard/UserOwnedPiggybanks/UserOwnedPiggybanks.jsx:
  - (3, 'Hardcoded string found')
Issues in components/Icons/CustomIcons.jsx:
  - (4, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
Issues in components/LandingPage/Footer.jsx:
  - (2, 'Hardcoded string found')
Issues in components/LandingPage/LandingPage.jsx:
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
  - (27, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/EditPiggybankModal/EditPiggybankModal.jsx:
  - (4, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (24, 'Hardcoded string found')
  - (26, 'Line exceeds 80 characters')
  - (26, 'Hardcoded string found')
  - (33, 'TODO found')
  - (37, 'Hardcoded string found')
  - (40, 'TODO found')
  - (40, 'Line exceeds 80 characters')
  - (40, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (43, 'TODO found')
  - (44, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/EditPiggybankModal/PaymentMethodsInput.jsx:
  - (1, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
Issues in components/PublicPiggybankPage/ManagePiggybankBar/ManagePiggybankBar.jsx:
  - (2, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
Issues in components/PublicPiggybankPage/ManagePiggybankBar/ShareButtonModal/ShareEmbedButton.jsx:
  - (2, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
Issues in components/PublicPiggybankPage/PaymentMethodButtonModal.jsx:
  - (2, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
Issues in pages/[piggybankName].js:
  - (2, 'Line exceeds 80 characters')
  - (5, 'TODO found')
  - (12, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'TODO found')
  - (22, 'Hardcoded string found')
Issues in pages/_document.jsx:
  - (4, 'Line exceeds 80 characters')
  - (4, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (11, 'Hardcoded string found')
Issues in server/middleware/requireBetaInvite.js:
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
Issues in server/middleware/requireFirebaseToken.js:
  - (6, 'Hardcoded string found')
Issues in src/embed-button/generate.js:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
Issues in src/paymentMethods.jsx:
  - (2, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (29, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
  - (32, 'Line exceeds 80 characters')
  - (32, 'Hardcoded string found')
  - (33, 'Line exceeds 80 characters')
  - (33, 'Hardcoded string found')
  - (34, 'Line exceeds 80 characters')
  - (34, 'Hardcoded string found')
  - (35, 'Line exceeds 80 characters')
  - (35, 'Hardcoded string found')
  - (37, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')
  - (38, 'Line exceeds 80 characters')
  - (38, 'Hardcoded string found')
  - (39, 'Line exceeds 80 characters')
  - (39, 'Hardcoded string found')
  - (40, 'Line exceeds 80 characters')
  - (40, 'Hardcoded string found')
  - (41, 'Line exceeds 80 characters')
  - (41, 'Hardcoded string found')
Issues in utils/auth/useUser.js:
  - (5, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (11, 'TODO found')
  - (13, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
