### ISSUE TITLE
Issue-basic auth working and v1 of logo

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#4]
Automated Review Comments
Issues in components/FirebaseAuth.js:
  - (8, 'Hardcoded string found')
Issues in components/logo/Logo.jsx:
  - (2, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (11, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
Issues in components/theme.js:
  - (4, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (29, 'Line exceeds 80 characters')
  - (30, 'Hardcoded string found')
Issues in package.json:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
Issues in pages/_document.js:
  - (14, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
Issues in pages/api/getFood.js:
  - (6, 'Hardcoded string found')
Issues in pages/index.js:
  - (2, 'Hardcoded string found')
Issues in yarn.lock:
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (24, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (56, 'Line exceeds 80 characters')
  - (57, 'Line exceeds 80 characters')
  - (59, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (66, 'Line exceeds 80 characters')
  - (67, 'Line exceeds 80 characters')
  - (69, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (78, 'Line exceeds 80 characters')
  - (79, 'Line exceeds 80 characters')
  - (81, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (87, 'Line exceeds 80 characters')
  - (88, 'Line exceeds 80 characters')
  - (92, 'Line exceeds 80 characters')
  - (93, 'Line exceeds 80 characters')
  - (95, 'Hardcoded string found')
  - (99, 'Line exceeds 80 characters')
  - (100, 'Line exceeds 80 characters')
  - (104, 'Line exceeds 80 characters')
  - (105, 'Line exceeds 80 characters')
  - (107, 'Hardcoded string found')
  - (108, 'Hardcoded string found')
  - (109, 'Hardcoded string found')
  - (110, 'Hardcoded string found')
  - (115, 'Line exceeds 80 characters')
  - (116, 'Line exceeds 80 characters')
  - (120, 'Line exceeds 80 characters')
  - (121, 'Line exceeds 80 characters')
  - (123, 'Hardcoded string found')
  - (124, 'Hardcoded string found')
  - (125, 'Hardcoded string found')
  - (126, 'Hardcoded string found')
  - (130, 'Line exceeds 80 characters')
  - (131, 'Line exceeds 80 characters')
  - (133, 'Hardcoded string found')
  - (138, 'Line exceeds 80 characters')
  - (139, 'Line exceeds 80 characters')
  - (143, 'Line exceeds 80 characters')
  - (144, 'Line exceeds 80 characters')
  - (148, 'Line exceeds 80 characters')
  - (149, 'Line exceeds 80 characters')
  - (153, 'Line exceeds 80 characters')
  - (154, 'Line exceeds 80 characters')
  - (158, 'Line exceeds 80 characters')
  - (160, 'Line exceeds 80 characters')
  - (165, 'Line exceeds 80 characters')
  - (166, 'Line exceeds 80 characters')
  - (168, 'Hardcoded string found')
  - (169, 'Hardcoded string found')
  - (173, 'Line exceeds 80 characters')
  - (174, 'Line exceeds 80 characters')
  - (176, 'Hardcoded string found')
  - (181, 'Line exceeds 80 characters')
  - (182, 'Line exceeds 80 characters')
  - (186, 'Line exceeds 80 characters')
  - (187, 'Line exceeds 80 characters')
  - (189, 'Hardcoded string found')
  - (195, 'Line exceeds 80 characters')
  - (196, 'Line exceeds 80 characters')
  - (200, 'Line exceeds 80 characters')
  - (201, 'Line exceeds 80 characters')
  - (203, 'Hardcoded string found')
  - (207, 'Line exceeds 80 characters')
  - (208, 'Line exceeds 80 characters')
  - (210, 'Hardcoded string found')
  - (214, 'Line exceeds 80 characters')
  - (215, 'Line exceeds 80 characters')
  - (217, 'Hardcoded string found')
  - (221, 'Line exceeds 80 characters')
  - (222, 'Line exceeds 80 characters')
  - (228, 'Line exceeds 80 characters')
  - (229, 'Line exceeds 80 characters')
  - (233, 'Line exceeds 80 characters')
  - (234, 'Line exceeds 80 characters')
  - (236, 'Hardcoded string found')
  - (240, 'Line exceeds 80 characters')
  - (241, 'Line exceeds 80 characters')
  - (243, 'Hardcoded string found')
  - (247, 'Line exceeds 80 characters')
  - (248, 'Line exceeds 80 characters')
  - (250, 'Hardcoded string found')
  - (254, 'Line exceeds 80 characters')
  - (255, 'Line exceeds 80 characters')
  - (257, 'Hardcoded string found')
  - (261, 'Line exceeds 80 characters')
  - (262, 'Line exceeds 80 characters')
  - (264, 'Hardcoded string found')
  - (268, 'Line exceeds 80 characters')
  - (269, 'Line exceeds 80 characters')
  - (271, 'Hardcoded string found')
  - (272, 'Hardcoded string found')
  - (277, 'Line exceeds 80 characters')
  - (278, 'Line exceeds 80 characters')
  - (280, 'Hardcoded string found')
  - (284, 'Line exceeds 80 characters')
  - (285, 'Line exceeds 80 characters')
  - (287, 'Hardcoded string found')
  - (291, 'Line exceeds 80 characters')
  - (292, 'Line exceeds 80 characters')
  - (294, 'Hardcoded string found')
  - (295, 'Hardcoded string found')
  - (299, 'Line exceeds 80 characters')
  - (301, 'Line exceeds 80 characters')
  - (302, 'Line exceeds 80 characters')
  - (306, 'Line exceeds 80 characters')
  - (307, 'Line exceeds 80 characters')
  - (311, 'Line exceeds 80 characters')
  - (312, 'Line exceeds 80 characters')
  - (316, 'Line exceeds 80 characters')
  - (317, 'Line exceeds 80 characters')
  - (319, 'Hardcoded string found')
  - (323, 'Line exceeds 80 characters')
  - (324, 'Line exceeds 80 characters')
  - (326, 'Hardcoded string found')
  - (331, 'Line exceeds 80 characters')
  - (332, 'Line exceeds 80 characters')
  - (338, 'Line exceeds 80 characters')
  - (343, 'Line exceeds 80 characters')
  - (344, 'Line exceeds 80 characters')
  - (348, 'Line exceeds 80 characters')
  - (350, 'Line exceeds 80 characters')
  - (351, 'Line exceeds 80 characters')
  - (355, 'Line exceeds 80 characters')
  - (356, 'Line exceeds 80 characters')
  - (362, 'Line exceeds 80 characters')
  - (370, 'Line exceeds 80 characters')
  - (371, 'Line exceeds 80 characters')
  - (373, 'Hardcoded string found')
  - (374, 'Hardcoded string found')
  - (375, 'Hardcoded string found')
  - (376, 'Hardcoded string found')
  - (386, 'Line exceeds 80 characters')
  - (387, 'Line exceeds 80 characters')
  - (389, 'Hardcoded string found')
  - (395, 'Line exceeds 80 characters')
  - (398, 'Line exceeds 80 characters')
  - (399, 'Line exceeds 80 characters')
  - (403, 'Line exceeds 80 characters')
  - (404, 'Line exceeds 80 characters')
  - (408, 'Line exceeds 80 characters')
  - (415, 'Line exceeds 80 characters')
  - (416, 'Line exceeds 80 characters')
  - (420, 'Line exceeds 80 characters')
  - (428, 'Line exceeds 80 characters')
  - (429, 'Line exceeds 80 characters')
  - (437, 'Line exceeds 80 characters')
  - (438, 'Line exceeds 80 characters')
  - (440, 'Line exceeds 80 characters')
  - (446, 'Line exceeds 80 characters')
  - (447, 'Line exceeds 80 characters')
  - (451, 'Line exceeds 80 characters')
  - (452, 'Line exceeds 80 characters')
  - (459, 'Line exceeds 80 characters')
  - (460, 'Line exceeds 80 characters')
  - (467, 'Line exceeds 80 characters')
  - (469, 'Line exceeds 80 characters')
  - (475, 'Line exceeds 80 characters')
  - (476, 'Line exceeds 80 characters')
  - (478, 'Line exceeds 80 characters')
  - (483, 'Line exceeds 80 characters')
  - (484, 'Line exceeds 80 characters')
  - (490, 'Line exceeds 80 characters')
  - (492, 'Line exceeds 80 characters')
  - (497, 'Line exceeds 80 characters')
  - (498, 'Line exceeds 80 characters')
  - (500, 'Hardcoded string found')
  - (508, 'Line exceeds 80 characters')
  - (515, 'Line exceeds 80 characters')
  - (516, 'Line exceeds 80 characters')
  - (520, 'Line exceeds 80 characters')
  - (521, 'Line exceeds 80 characters')
  - (525, 'Line exceeds 80 characters')
  - (532, 'Line exceeds 80 characters')
  - (533, 'Line exceeds 80 characters')
  - (537, 'Line exceeds 80 characters')
  - (539, 'Line exceeds 80 characters')
  - (540, 'Line exceeds 80 characters')
  - (544, 'Line exceeds 80 characters')
  - (545, 'Line exceeds 80 characters')
  - (547, 'Hardcoded string found')
  - (548, 'Hardcoded string found')
  - (553, 'Line exceeds 80 characters')
  - (560, 'Line exceeds 80 characters')
  - (561, 'Line exceeds 80 characters')
  - (567, 'Line exceeds 80 characters')
  - (574, 'Line exceeds 80 characters')
  - (579, 'Line exceeds 80 characters')
  - (586, 'Line exceeds 80 characters')
  - (587, 'Line exceeds 80 characters')
  - (591, 'Line exceeds 80 characters')
  - (598, 'Line exceeds 80 characters')
  - (599, 'Line exceeds 80 characters')
  - (603, 'Line exceeds 80 characters')
  - (610, 'Line exceeds 80 characters')
  - (611, 'Line exceeds 80 characters')
  - (617, 'Line exceeds 80 characters')
  - (619, 'Line exceeds 80 characters')
  - (624, 'Line exceeds 80 characters')
  - (625, 'Line exceeds 80 characters')
  - (632, 'Line exceeds 80 characters')
  - (634, 'Line exceeds 80 characters')
  - (635, 'Line exceeds 80 characters')
  - (639, 'Line exceeds 80 characters')
  - (644, 'Line exceeds 80 characters')
  - (645, 'Line exceeds 80 characters')
  - (649, 'Line exceeds 80 characters')
  - (651, 'Line exceeds 80 characters')
  - (652, 'Line exceeds 80 characters')
  - (656, 'Line exceeds 80 characters')
  - (657, 'Line exceeds 80 characters')
  - (661, 'Line exceeds 80 characters')
  - (668, 'Line exceeds 80 characters')
  - (673, 'Line exceeds 80 characters')
  - (680, 'Line exceeds 80 characters')
  - (681, 'Line exceeds 80 characters')
  - (687, 'Line exceeds 80 characters')
  - (694, 'Line exceeds 80 characters')
  - (695, 'Line exceeds 80 characters')
  - (697, 'Hardcoded string found')
  - (704, 'Line exceeds 80 characters')
  - (706, 'Line exceeds 80 characters')
  - (707, 'Line exceeds 80 characters')
  - (711, 'Line exceeds 80 characters')
  - (712, 'Line exceeds 80 characters')
  - (716, 'Line exceeds 80 characters')
  - (723, 'Line exceeds 80 characters')
  - (724, 'Line exceeds 80 characters')
  - (728, 'Line exceeds 80 characters')
  - (730, 'Line exceeds 80 characters')
  - (731, 'Line exceeds 80 characters')
  - (736, 'Line exceeds 80 characters')
  - (737, 'Line exceeds 80 characters')
  - (744, 'Line exceeds 80 characters')
  - (745, 'Line exceeds 80 characters')
  - (752, 'Line exceeds 80 characters')
  - (753, 'Line exceeds 80 characters')
  - (755, 'Hardcoded string found')
  - (759, 'Line exceeds 80 characters')
  - (767, 'Line exceeds 80 characters')
  - (768, 'Line exceeds 80 characters')
  - (770, 'Hardcoded string found')
  - (779, 'Line exceeds 80 characters')
  - (780, 'Line exceeds 80 characters')
  - (782, 'Line exceeds 80 characters')
  - (783, 'Line exceeds 80 characters')
  - (787, 'Line exceeds 80 characters')
  - (788, 'Line exceeds 80 characters')
  - (790, 'Hardcoded string found')
  - (795, 'Line exceeds 80 characters')
  - (797, 'Line exceeds 80 characters')
  - (798, 'Line exceeds 80 characters')
  - (802, 'Line exceeds 80 characters')
  - (803, 'Line exceeds 80 characters')
  - (807, 'Line exceeds 80 characters')
  - (809, 'Line exceeds 80 characters')
  - (815, 'Line exceeds 80 characters')
  - (816, 'Line exceeds 80 characters')
  - (818, 'Line exceeds 80 characters')
  - (819, 'Line exceeds 80 characters')
  - (823, 'Line exceeds 80 characters')
  - (830, 'Line exceeds 80 characters')
  - (838, 'Line exceeds 80 characters')
  - (846, 'Line exceeds 80 characters')
  - (847, 'Line exceeds 80 characters')
  - (849, 'Hardcoded string found')
  - (850, 'Hardcoded string found')
  - (851, 'Hardcoded string found')
  - (852, 'Hardcoded string found')
  - (853, 'Hardcoded string found')
  - (854, 'Hardcoded string found')
  - (855, 'Hardcoded string found')
  - (856, 'Hardcoded string found')
  - (857, 'Hardcoded string found')
  - (858, 'Hardcoded string found')
  - (859, 'Hardcoded string found')
  - (860, 'Hardcoded string found')
  - (865, 'Line exceeds 80 characters')
  - (872, 'Line exceeds 80 characters')
  - (873, 'Line exceeds 80 characters')
  - (875, 'Hardcoded string found')
  - (876, 'Hardcoded string found')
  - (877, 'Hardcoded string found')
  - (881, 'Line exceeds 80 characters')
  - (886, 'Line exceeds 80 characters')
  - (888, 'Line exceeds 80 characters')
  - (889, 'Line exceeds 80 characters')
  - (894, 'Line exceeds 80 characters')
  - (895, 'Line exceeds 80 characters')
  - (899, 'Line exceeds 80 characters')
  - (900, 'Line exceeds 80 characters')
  - (904, 'Line exceeds 80 characters')
  - (911, 'Line exceeds 80 characters')
  - (912, 'Line exceeds 80 characters')
  - (916, 'Line exceeds 80 characters')
  - (917, 'Line exceeds 80 characters')
  - (919, 'Hardcoded string found')
  - (924, 'Line exceeds 80 characters')
  - (925, 'Line exceeds 80 characters')
  - (927, 'Hardcoded string found')
  - (931, 'Line exceeds 80 characters')
  - (932, 'Line exceeds 80 characters')
  - (939, 'Line exceeds 80 characters')
  - (941, 'Line exceeds 80 characters')
  - (942, 'Line exceeds 80 characters')
  - (946, 'Line exceeds 80 characters')
  - (947, 'Line exceeds 80 characters')
  - (953, 'Line exceeds 80 characters')
  - (955, 'Line exceeds 80 characters')
  - (956, 'Line exceeds 80 characters')
  - (960, 'Line exceeds 80 characters')
  - (961, 'Line exceeds 80 characters')
  - (965, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
