### ISSUE TITLE
Issue-fix lint

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#403]
Automated Review Comments
Issues in components/PublicPiggybankPage/EditPiggybankModal/PaymentMethodsInput.jsx:
  - (1, 'Line exceeds 80 characters')
  - (2, 'TODO found')
  - (2, 'Line exceeds 80 characters')
  - (4, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
