### ISSUE TITLE
Issue-fix page title on Dashboard and Public Piggybank pages

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#411]
Automated Review Comments
Issues in components/Dashboard/Dashboard.jsx:
  - (1, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/PublicPiggybankPage.jsx:
  - (6, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
