### ISSUE TITLE
Issue-basic upload working. next: display on front end

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#415]
Automated Review Comments
Issues in components/PublicPiggybankPage/EditPiggybankModal/AvatarInput.jsx:
  - (2, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (24, 'Line exceeds 80 characters')
  - (24, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (42, 'Line exceeds 80 characters')
Issues in components/PublicPiggybankPage/EditPiggybankModal/AvatarInput.test.js:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in utils/client/storage.js:
  - (2, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
