### ISSUE TITLE
Issue-uploaded image showing up in UI

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#417]
Automated Review Comments
Issues in components/PublicPiggybankPage/EditPiggybankModal/AvatarInput.jsx:
  - (1, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
Issues in components/PublicPiggybankPage/PublicPiggybankPage.jsx:
  - (10, 'TODO found')
  - (11, 'TODO found')
  - (13, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (30, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/photo/Photo.jsx:
  - (2, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
Issues in utils/storage/image-paths.js:
  - (2, 'Line exceeds 80 characters')
  - (3, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
