### ISSUE TITLE
Issue-buggy transition between landing and dashboard

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#42]
Automated Review Comments
Issues in components/Dashboard/Dashboard.jsx:
  - (1, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
Issues in components/LandingPage/LandingPage.jsx:
  - (2, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
