### ISSUE TITLE
Issue-progress. displaying appropriate error messages, reloading images on upload

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#421]
Automated Review Comments
Issues in .eslintrc:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/EditPiggybankModal/AvatarInput.jsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (22, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (32, 'Line exceeds 80 characters')
  - (32, 'Hardcoded string found')
  - (36, 'TODO found')
  - (40, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (45, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (53, 'Line exceeds 80 characters')
  - (69, 'Line exceeds 80 characters')
  - (69, 'Hardcoded string found')
  - (77, 'Line exceeds 80 characters')
  - (79, 'Line exceeds 80 characters')
  - (81, 'Line exceeds 80 characters')
  - (87, 'Line exceeds 80 characters')
  - (90, 'Line exceeds 80 characters')
  - (94, 'Hardcoded string found')
  - (96, 'Line exceeds 80 characters')
  - (99, 'Line exceeds 80 characters')
Issues in components/PublicPiggybankPage/EditPiggybankModal/EditPiggybankModal.jsx:
  - (14, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Line exceeds 80 characters')
  - (40, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (83, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (101, 'Hardcoded string found')
  - (104, 'Hardcoded string found')
  - (136, 'Hardcoded string found')
  - (142, 'Hardcoded string found')
  - (144, 'Hardcoded string found')
  - (146, 'Hardcoded string found')
  - (149, 'Line exceeds 80 characters')
  - (168, 'Line exceeds 80 characters')
  - (183, 'Hardcoded string found')
  - (184, 'Line exceeds 80 characters')
  - (187, 'Hardcoded string found')
  - (215, 'Hardcoded string found')
  - (230, 'Hardcoded string found')
  - (233, 'Hardcoded string found')
  - (234, 'Hardcoded string found')
  - (235, 'Hardcoded string found')
  - (248, 'Hardcoded string found')
  - (251, 'Hardcoded string found')
  - (283, 'Hardcoded string found')
  - (289, 'Hardcoded string found')
  - (291, 'Hardcoded string found')
  - (293, 'Hardcoded string found')
  - (296, 'Line exceeds 80 characters')
Issues in components/PublicPiggybankPage/PublicPiggybankPage.jsx:
  - (8, 'TODO found')
  - (17, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/context/avatar-context.tsx:
  - (2, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
Issues in components/PublicPiggybankPage/photo/Photo.jsx:
  - (2, 'Hardcoded string found')
  - (11, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/photo/Photo.module.css:
  - (2, 'Line exceeds 80 characters')
Issues in next-env.d.ts:
  - (2, 'Hardcoded string found')
Issues in tsconfig.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (27, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
