### ISSUE TITLE
Issue-fix app crash on add new payment method

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#427]
Automated Review Comments
Issues in .eslintrc:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/EditPiggybankModal/EditPiggybankModal.jsx:
  - (1, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (57, 'Line exceeds 80 characters')
  - (60, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (103, 'Hardcoded string found')
  - (106, 'Hardcoded string found')
  - (107, 'Hardcoded string found')
  - (108, 'Hardcoded string found')
  - (121, 'Hardcoded string found')
  - (124, 'Hardcoded string found')
  - (156, 'Hardcoded string found')
  - (162, 'Hardcoded string found')
  - (164, 'Hardcoded string found')
  - (166, 'Hardcoded string found')
  - (169, 'Line exceeds 80 characters')
  - (179, 'Hardcoded string found')
  - (182, 'Hardcoded string found')
  - (185, 'Hardcoded string found')
  - (188, 'Hardcoded string found')
  - (207, 'Line exceeds 80 characters')
  - (228, 'Line exceeds 80 characters')
  - (242, 'Hardcoded string found')
  - (243, 'Line exceeds 80 characters')
  - (246, 'Hardcoded string found')
  - (274, 'Hardcoded string found')
  - (289, 'Hardcoded string found')
  - (292, 'Hardcoded string found')
  - (293, 'Hardcoded string found')
  - (294, 'Hardcoded string found')
  - (307, 'Hardcoded string found')
  - (310, 'Hardcoded string found')
  - (342, 'Hardcoded string found')
  - (348, 'Hardcoded string found')
  - (350, 'Hardcoded string found')
  - (352, 'Hardcoded string found')
  - (355, 'Line exceeds 80 characters')
Issues in components/PublicPiggybankPage/EditPiggybankModal/PaymentMethodsInput.jsx:
  - (4, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/PublicPiggybankPage.jsx:
  - (15, 'TODO found')
  - (16, 'TODO found')
  - (17, 'TODO found')
  - (19, 'Hardcoded string found')
  - (21, 'Line exceeds 80 characters')
  - (35, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
Issues in package.json:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
Issues in yarn.lock:
  - (2, 'Line exceeds 80 characters')
  - (3, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
