### ISSUE TITLE
Issue-cleanup. need to fix edit payment methods - bug with preferred being set automatically as array instead of string

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#443]
Automated Review Comments
Issues in components/PublicPiggybankPage/EditPiggybankModal/EditPiggybankModal.jsx:
  - (6, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (30, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
