### ISSUE TITLE
Issue-fix placement of ModalBody

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#445]
Automated Review Comments
Issues in components/PublicPiggybankPage/EditPiggybankModal/EditPiggybankModal.jsx:
  - (33, 'Hardcoded string found')
  - (34, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (60, 'Line exceeds 80 characters')
  - (63, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (105, 'Hardcoded string found')
  - (123, 'Hardcoded string found')
  - (126, 'Hardcoded string found')
  - (127, 'Hardcoded string found')
  - (128, 'Hardcoded string found')
  - (137, 'Hardcoded string found')
  - (147, 'Hardcoded string found')
  - (150, 'Hardcoded string found')
  - (156, 'Hardcoded string found')
  - (157, 'Hardcoded string found')
  - (158, 'Hardcoded string found')
  - (186, 'Hardcoded string found')
  - (189, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/EditPiggybankModal/PaymentMethodsInput.jsx:
  - (1, 'Line exceeds 80 characters')
  - (3, 'TODO found')
  - (3, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
