### ISSUE TITLE
Issue-i dont know why but payment methods input is fixed after removing tabs and moving around modal components

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#449]
Automated Review Comments
Issues in components/PublicPiggybankPage/EditPiggybankModal/EditPiggybankModal.jsx:
  - (20, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (33, 'Line exceeds 80 characters')
Issues in components/PublicPiggybankPage/EditPiggybankModal/PaymentMethodsInput.jsx:
  - (1, 'Line exceeds 80 characters')
  - (3, 'TODO found')
  - (3, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
