### ISSUE TITLE
Issue-delete associated Avatar on delete of a Coindrop

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#451]
Automated Review Comments
Issues in components/Dashboard/UserOwnedPiggybanks/PiggybankListItem/DeleteButton.jsx:
  - (5, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (22, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/EditPiggybankModal/AvatarInput.jsx:
  - (5, 'Line exceeds 80 characters')
Issues in src/db/config/firebase-firestore.rules:
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
