### ISSUE TITLE
Issue-fix piggybank create by passing correct variable name

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#457]
Automated Review Comments
Issues in components/Dashboard/UserOwnedPiggybanks/PiggybankListItem/DeleteButton.jsx:
  - (4, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/EditPiggybankModal/EditPiggybankModal.jsx:
  - (3, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
Issues in utils/hooks/useCreatePiggybank.js:
  - (1, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
