### ISSUE TITLE
Issue-next serving optimized images, but probably having to reoptimize every request due to img src query param.

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#459]
Automated Review Comments
Issues in components/PublicPiggybankPage/avatar/Avatar.jsx:
  - (2, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/avatar/Avatar.module.css:
  - (2, 'Line exceeds 80 characters')
Issues in next.config.js:
  - (2, 'Hardcoded string found')
Issues in package.json:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
