### ISSUE TITLE
Issue-update invalid URL error msg

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#46]
Automated Review Comments
Issues in components/LandingPage/LandingPage.jsx:
  - (1, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (26, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
  - (33, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
