### ISSUE TITLE
Issue-generate unique avatar urls for next/image optimization. convert some files to typescript.

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#461]
Automated Review Comments
Issues in components/Dashboard/UserOwnedPiggybanks/PiggybankListItem/DeleteButton.tsx:
  - (2, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (35, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/EditPiggybankModal/AvatarInput.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')
  - (34, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (45, 'Line exceeds 80 characters')
  - (45, 'Hardcoded string found')
  - (51, 'Line exceeds 80 characters')
  - (54, 'Line exceeds 80 characters')
  - (56, 'Line exceeds 80 characters')
  - (61, 'Line exceeds 80 characters')
  - (61, 'Hardcoded string found')
  - (82, 'Line exceeds 80 characters')
  - (84, 'Line exceeds 80 characters')
  - (86, 'Line exceeds 80 characters')
  - (88, 'Line exceeds 80 characters')
  - (96, 'Hardcoded string found')
  - (100, 'Line exceeds 80 characters')
  - (100, 'Hardcoded string found')
  - (105, 'Line exceeds 80 characters')
  - (105, 'Hardcoded string found')
  - (108, 'Hardcoded string found')
  - (114, 'Hardcoded string found')
  - (124, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/EditPiggybankModal/EditPiggybankModal.jsx:
  - (2, 'Line exceeds 80 characters')
  - (3, 'Line exceeds 80 characters')
  - (4, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (11, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (17, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/PublicPiggybankPage.jsx:
  - (8, 'TODO found')
  - (16, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/avatar/Avatar.tsx:
  - (2, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
Issues in pages/api/createPiggybank.ts:
  - (4, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (22, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (43, 'Line exceeds 80 characters')
  - (52, 'Line exceeds 80 characters')
  - (52, 'Hardcoded string found')
  - (53, 'Line exceeds 80 characters')
  - (53, 'Hardcoded string found')
  - (59, 'TODO found')
  - (68, 'Line exceeds 80 characters')
  - (75, 'Hardcoded string found')
  - (82, 'Line exceeds 80 characters')
Issues in utils/storage/image-paths.ts:
  - (9, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
