### ISSUE TITLE
Issue-use next/image for avatar placeholder

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#463]
Automated Review Comments
Issues in components/PublicPiggybankPage/EditPiggybankModal/AvatarInput.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (13, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
