### ISSUE TITLE
Issue-fix name conflict of next/image and javascript built-in Image

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#465]
Automated Review Comments
Issues in components/PublicPiggybankPage/EditPiggybankModal/AvatarInput.tsx:
  - (2, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (11, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (21, 'Hardcoded string found')
  - (22, 'Line exceeds 80 characters')
  - (22, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
