### ISSUE TITLE
Issue-better button layout for upload/remove image

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#467]
Automated Review Comments
Issues in components/PublicPiggybankPage/EditPiggybankModal/AvatarInput.tsx:
  - (2, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (11, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
  - (25, 'Hardcoded string found')
  - (30, 'Line exceeds 80 characters')
  - (30, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (41, 'Line exceeds 80 characters')
  - (41, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (76, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
