### ISSUE TITLE
Issue-fix typescript errors

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#469]
Automated Review Comments
Issues in components/PublicPiggybankPage/EditPiggybankModal/AvatarInput.tsx:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
Issues in utils/auth/useUser.ts:
  - (2, 'Hardcoded string found')
  - (26, 'TODO found')
  - (28, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
