### ISSUE TITLE
Issue-clean up image-paths.ts

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#473]
Automated Review Comments
Issues in pages/api/createPiggybank.ts:
  - (1, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
Issues in utils/storage/image-paths.ts:
  - (9, 'Hardcoded string found')
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
