### ISSUE TITLE
Issue-fix typescript warnings

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#475]
Automated Review Comments
Issues in components/PublicPiggybankPage/EditPiggybankModal/AvatarInput.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (30, 'Line exceeds 80 characters')
Issues in components/PublicPiggybankPage/EditPiggybankModal/EditPiggybankModal.jsx:
  - (1, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/avatar/Avatar.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
Issues in pages/fileinput.tsx:
  - (2, 'Hardcoded string found')
  - (8, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
