### ISSUE TITLE
Issue-fix typescript warning for file input ref with forwardRef. fix create piggybank from scratch error

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#477]
Automated Review Comments
Issues in components/Buttons/file-input/FileInput.tsx:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (37, 'Line exceeds 80 characters')
  - (45, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/EditPiggybankModal/AvatarInput.tsx:
  - (1, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (21, 'Hardcoded string found')
Issues in pages/api/createPiggybank.ts:
  - (8, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
