### ISSUE TITLE
Issue-create deleteImage function. dont attempt delete if null storageId is passed.

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#487]
Automated Review Comments
Issues in components/Dashboard/UserOwnedPiggybanks/PiggybankListItem/DeleteButton.tsx:
  - (5, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/EditPiggybankModal/AvatarInput.tsx:
  - (7, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (21, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
Issues in src/db/mutations/delete-image.ts:
  - (11, 'Line exceeds 80 characters')
  - (17, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
