### ISSUE TITLE
Issue-run tests with github actions (#69)

* github actions

* test github actions

* test github actions

* wip [skip ci]

* wip [skip ci]

* wip [skip ci]

* remove private files

* remove cypress temp files

* delete unused files

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#491]
Automated Review Comments
Issues in .github/workflows/node.js.yml:
  - (2, 'Line exceeds 80 characters')
  - (3, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')
Issues in package.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (10, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
