### ISSUE TITLE
Issue-🐛 Error: Dynamic server usage: Route / couldn't be rendered statically because it used cookies.などのエラーの暫定対応

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#497]
Automated Review Comments
Issues in src/app/itineraries/[id]/page.tsx:
  - (3, 'Line exceeds 80 characters')
  - (22, 'TODO found')
  - (24, 'Line exceeds 80 characters')
Issues in src/app/layout.tsx:
  - (3, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
