### ISSUE TITLE
Issue-list user owned piggybanks in dashboard

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#56]
Automated Review Comments
Issues in components/Dashboard/Dashboard.jsx:
  - (4, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
Issues in components/Dashboard/UserOwnedPiggybanks.jsx:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (32, 'Line exceeds 80 characters')
  - (35, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
Issues in components/Icons/CustomIcons.jsx:
  - (1, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (32, 'Hardcoded string found')
  - (37, 'Line exceeds 80 characters')
  - (42, 'Line exceeds 80 characters')
  - (42, 'Hardcoded string found')
  - (47, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (50, 'Line exceeds 80 characters')
  - (51, 'Line exceeds 80 characters')
  - (52, 'Line exceeds 80 characters')
  - (57, 'Hardcoded string found')
  - (58, 'Line exceeds 80 characters')
  - (59, 'Line exceeds 80 characters')
  - (60, 'Line exceeds 80 characters')
  - (68, 'Line exceeds 80 characters')
  - (68, 'Hardcoded string found')
  - (75, 'Line exceeds 80 characters')
  - (76, 'Line exceeds 80 characters')
  - (77, 'Line exceeds 80 characters')
  - (81, 'Line exceeds 80 characters')
  - (82, 'Line exceeds 80 characters')
  - (83, 'Line exceeds 80 characters')
  - (89, 'Line exceeds 80 characters')
  - (89, 'Hardcoded string found')
  - (93, 'Line exceeds 80 characters')
  - (93, 'Hardcoded string found')
  - (97, 'Line exceeds 80 characters')
  - (98, 'Line exceeds 80 characters')
  - (99, 'Line exceeds 80 characters')
  - (105, 'Line exceeds 80 characters')
  - (112, 'Line exceeds 80 characters')
  - (113, 'Line exceeds 80 characters')
  - (114, 'Line exceeds 80 characters')
  - (115, 'Line exceeds 80 characters')
  - (120, 'Line exceeds 80 characters')
  - (120, 'Hardcoded string found')
  - (125, 'Line exceeds 80 characters')
  - (130, 'Line exceeds 80 characters')
  - (130, 'Hardcoded string found')
  - (134, 'Line exceeds 80 characters')
  - (134, 'Hardcoded string found')
  - (139, 'Line exceeds 80 characters')
  - (139, 'Hardcoded string found')
  - (145, 'Line exceeds 80 characters')
  - (146, 'Line exceeds 80 characters')
  - (153, 'Line exceeds 80 characters')
  - (154, 'Line exceeds 80 characters')
  - (155, 'Line exceeds 80 characters')
  - (156, 'Line exceeds 80 characters')
  - (157, 'Line exceeds 80 characters')
  - (158, 'Line exceeds 80 characters')
  - (163, 'Hardcoded string found')
  - (164, 'Line exceeds 80 characters')
  - (165, 'Line exceeds 80 characters')
  - (166, 'Line exceeds 80 characters')
  - (174, 'Line exceeds 80 characters')
  - (174, 'Hardcoded string found')
  - (177, 'Line exceeds 80 characters')
  - (177, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/PublicPiggybankPage.jsx:
  - (2, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (7, 'TODO found')
  - (7, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
Issues in components/theme.js:
  - (6, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
  - (24, 'Hardcoded string found')
Issues in utils/client/db.js:
  - (2, 'Hardcoded string found')
  - (3, 'TODO found')

**Comment by satokihanada** [comment]
I got it.
