### ISSUE TITLE
Issue-piggybank context + dashboard updates (#5)

* wip [skip ci]

* cleanup

* rename logo folder

* rename logo folder

* wip [skip ci]

* wip [skip ci]

* wip [skip ci]

* wip [skip ci]

* wip [skip ci]

* update readme

* wip [skip ci]

* wip [skip ci]

* wip [skip ci]

* wip [skip ci]

* wip [skip ci]

* wip [skip ci]

* wip [skip ci]

* wip [skip ci]

* wip [skip ci]

* wip [skip ci]

* wip [skip ci]

* wip [skip ci]

* wip [skip ci]

* wip [skip ci]

* wip [skip ci]

* wip [skip ci]

* wip [skip ci]

* add theme colors, next up: edit page

* wip [skip ci]

* wip [skip ci]

* wip [skip ci]

* edit modal updates

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#62]
Automated Review Comments
Issues in .eslintrc:
  - (6, 'Line exceeds 80 characters')
Issues in .vscode/extensions.txt:
  - (2, 'TODO found')
  - (2, 'Hardcoded string found')
Issues in README.md:
  - (11, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')
  - (43, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
  - (50, 'Line exceeds 80 characters')
  - (56, 'Line exceeds 80 characters')
  - (57, 'Line exceeds 80 characters')
  - (59, 'Line exceeds 80 characters')
  - (61, 'Line exceeds 80 characters')
  - (62, 'Line exceeds 80 characters')
  - (66, 'Line exceeds 80 characters')
  - (69, 'TODO found')
  - (69, 'Line exceeds 80 characters')
Issues in components/AppContext/AppContext.jsx:
  - (2, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
Issues in components/Auth/AuthModal.jsx:
  - (2, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (17, 'Hardcoded string found')
Issues in components/Auth/FirebaseAuth.jsx:
  - (2, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
  - (34, 'Hardcoded string found')
Issues in components/CreatePiggybankInput/CreatePiggybankInput.jsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (21, 'Hardcoded string found')
  - (22, 'TODO found')
  - (23, 'Hardcoded string found')
  - (32, 'TODO found')
  - (34, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (40, 'Line exceeds 80 characters')
  - (42, 'Line exceeds 80 characters')
  - (43, 'Line exceeds 80 characters')
  - (58, 'Line exceeds 80 characters')
  - (59, 'Line exceeds 80 characters')
  - (77, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (102, 'Hardcoded string found')
  - (103, 'Line exceeds 80 characters')
  - (103, 'Hardcoded string found')
  - (104, 'Line exceeds 80 characters')
  - (104, 'Hardcoded string found')
  - (105, 'Line exceeds 80 characters')
  - (105, 'Hardcoded string found')
  - (106, 'Hardcoded string found')
  - (108, 'Hardcoded string found')
  - (114, 'Hardcoded string found')
  - (120, 'Hardcoded string found')
Issues in components/Dashboard/Dashboard.jsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (21, 'Hardcoded string found')
  - (24, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (38, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
Issues in components/Dashboard/UserOwnedPiggybanks/AddPiggybankListItem/AddPiggybankListItem.jsx:
  - (2, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (60, 'Line exceeds 80 characters')
Issues in components/Dashboard/UserOwnedPiggybanks/PiggybankListItem.jsx:
  - (2, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
Issues in components/Dashboard/UserOwnedPiggybanks/PiggybankListItem/DeleteButton.jsx:
  - (2, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
Issues in components/Dashboard/UserOwnedPiggybanks/UserOwnedPiggybanks.jsx:
  - (3, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (33, 'Line exceeds 80 characters')
  - (52, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
Issues in components/Icons/CustomIcons.jsx:
  - (2, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (11, 'Line exceeds 80 characters')
  - (11, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
  - (36, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (41, 'Hardcoded string found')
  - (46, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (50, 'Line exceeds 80 characters')
  - (51, 'Line exceeds 80 characters')
  - (56, 'Hardcoded string found')
  - (57, 'Line exceeds 80 characters')
  - (58, 'Line exceeds 80 characters')
  - (59, 'Line exceeds 80 characters')
  - (68, 'Line exceeds 80 characters')
  - (68, 'Hardcoded string found')
  - (71, 'Line exceeds 80 characters')
  - (71, 'Hardcoded string found')
  - (75, 'Line exceeds 80 characters')
  - (75, 'Hardcoded string found')
  - (79, 'Line exceeds 80 characters')
  - (79, 'Hardcoded string found')
  - (85, 'Line exceeds 80 characters')
  - (86, 'Line exceeds 80 characters')
  - (87, 'Line exceeds 80 characters')
  - (96, 'Line exceeds 80 characters')
  - (102, 'Line exceeds 80 characters')
  - (107, 'Line exceeds 80 characters')
  - (113, 'Hardcoded string found')
  - (115, 'Line exceeds 80 characters')
  - (116, 'Line exceeds 80 characters')
  - (122, 'Line exceeds 80 characters')
  - (122, 'Hardcoded string found')
  - (127, 'Line exceeds 80 characters')
  - (128, 'Line exceeds 80 characters')
  - (133, 'Hardcoded string found')
  - (134, 'Line exceeds 80 characters')
  - (135, 'Line exceeds 80 characters')
  - (136, 'Line exceeds 80 characters')
  - (138, 'Line exceeds 80 characters')
  - (144, 'Line exceeds 80 characters')
  - (144, 'Hardcoded string found')
  - (149, 'Line exceeds 80 characters')
  - (149, 'Hardcoded string found')
  - (153, 'Line exceeds 80 characters')
  - (154, 'Line exceeds 80 characters')
  - (155, 'Line exceeds 80 characters')
  - (155, 'Hardcoded string found')
  - (159, 'Line exceeds 80 characters')
  - (168, 'Line exceeds 80 characters')
  - (168, 'Hardcoded string found')
  - (172, 'Line exceeds 80 characters')
  - (172, 'Hardcoded string found')
  - (175, 'Line exceeds 80 characters')
Issues in components/LandingPage/LandingPage.jsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (21, 'Hardcoded string found')
  - (22, 'Line exceeds 80 characters')
  - (22, 'Hardcoded string found')
  - (41, 'Line exceeds 80 characters')
  - (56, 'TODO found')
  - (57, 'Line exceeds 80 characters')
  - (57, 'Hardcoded string found')
  - (58, 'Line exceeds 80 characters')
  - (58, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (60, 'Line exceeds 80 characters')
  - (60, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (66, 'Line exceeds 80 characters')
  - (77, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (82, 'Line exceeds 80 characters')
  - (82, 'Hardcoded string found')
  - (83, 'Line exceeds 80 characters')
  - (83, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (85, 'Line exceeds 80 characters')
  - (85, 'Hardcoded string found')
  - (86, 'Line exceeds 80 characters')
  - (86, 'Hardcoded string found')
  - (87, 'Line exceeds 80 characters')
  - (87, 'Hardcoded string found')
  - (88, 'Line exceeds 80 characters')
  - (88, 'Hardcoded string found')
  - (89, 'Line exceeds 80 characters')
  - (89, 'Hardcoded string found')
  - (90, 'Line exceeds 80 characters')
  - (90, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (92, 'Line exceeds 80 characters')
  - (92, 'Hardcoded string found')
  - (93, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (95, 'Line exceeds 80 characters')
  - (95, 'Hardcoded string found')
  - (96, 'Line exceeds 80 characters')
  - (96, 'Hardcoded string found')
  - (97, 'Line exceeds 80 characters')
  - (97, 'Hardcoded string found')
  - (98, 'Line exceeds 80 characters')
  - (98, 'Hardcoded string found')
  - (99, 'Line exceeds 80 characters')
  - (99, 'Hardcoded string found')
  - (100, 'Line exceeds 80 characters')
  - (100, 'Hardcoded string found')
  - (107, 'Hardcoded string found')
  - (108, 'Line exceeds 80 characters')
  - (108, 'Hardcoded string found')
  - (109, 'Line exceeds 80 characters')
  - (109, 'Hardcoded string found')
  - (110, 'Line exceeds 80 characters')
  - (110, 'Hardcoded string found')
  - (111, 'Line exceeds 80 characters')
  - (111, 'Hardcoded string found')
  - (112, 'Line exceeds 80 characters')
  - (112, 'Hardcoded string found')
  - (113, 'Line exceeds 80 characters')
  - (113, 'Hardcoded string found')
  - (114, 'Line exceeds 80 characters')
  - (114, 'Hardcoded string found')
  - (115, 'Line exceeds 80 characters')
  - (115, 'Hardcoded string found')
  - (116, 'Line exceeds 80 characters')
  - (116, 'Hardcoded string found')
  - (117, 'Hardcoded string found')
  - (118, 'Hardcoded string found')
  - (119, 'Line exceeds 80 characters')
  - (119, 'Hardcoded string found')
  - (120, 'Line exceeds 80 characters')
  - (120, 'Hardcoded string found')
  - (121, 'Hardcoded string found')
  - (122, 'Hardcoded string found')
  - (123, 'Line exceeds 80 characters')
  - (123, 'Hardcoded string found')
  - (124, 'Line exceeds 80 characters')
  - (124, 'Hardcoded string found')
  - (125, 'Hardcoded string found')
  - (126, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/EditPiggybankModal/EditPiggybankModal.jsx:
  - (2, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (50, 'Line exceeds 80 characters')
  - (53, 'Line exceeds 80 characters')
  - (57, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (63, 'Line exceeds 80 characters')
  - (63, 'Hardcoded string found')
  - (65, 'Line exceeds 80 characters')
  - (65, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (80, 'Line exceeds 80 characters')
  - (90, 'TODO found')
  - (94, 'Hardcoded string found')
  - (98, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
  - (115, 'Hardcoded string found')
  - (116, 'Line exceeds 80 characters')
  - (118, 'Hardcoded string found')
  - (129, 'Hardcoded string found')
  - (147, 'Hardcoded string found')
  - (163, 'Hardcoded string found')
  - (166, 'Hardcoded string found')
  - (167, 'Hardcoded string found')
  - (168, 'Hardcoded string found')
  - (181, 'Hardcoded string found')
  - (184, 'Hardcoded string found')
  - (194, 'Line exceeds 80 characters')
  - (194, 'Hardcoded string found')
  - (196, 'Hardcoded string found')
  - (197, 'Hardcoded string found')
  - (201, 'Hardcoded string found')
  - (202, 'Hardcoded string found')
  - (204, 'Hardcoded string found')
  - (211, 'Hardcoded string found')
  - (212, 'Hardcoded string found')
  - (225, 'Hardcoded string found')
  - (227, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/ManagePiggybankBar/ManagePiggybankBar.jsx:
  - (2, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
  - (35, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/PaymentMethodButton.jsx:
  - (3, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (22, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Line exceeds 80 characters')
  - (33, 'Hardcoded string found')
  - (42, 'TODO found')
  - (42, 'Line exceeds 80 characters')
  - (46, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/PaymentMethodButtonModal.jsx:
  - (2, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/PoweredByCoindropLink.jsx:
  - (4, 'Line exceeds 80 characters')
  - (11, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (27, 'TODO found')
  - (27, 'Line exceeds 80 characters')
  - (30, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/PublicPiggybankDataContext.jsx:
  - (2, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/PublicPiggybankPage.jsx:
  - (5, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (16, 'TODO found')
  - (16, 'Line exceeds 80 characters')
  - (29, 'Hardcoded string found')
  - (32, 'TODO found')
  - (32, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (37, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (65, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (93, 'Hardcoded string found')
  - (96, 'Line exceeds 80 characters')
  - (106, 'Line exceeds 80 characters')
  - (106, 'Hardcoded string found')
  - (107, 'Line exceeds 80 characters')
  - (109, 'Line exceeds 80 characters')
  - (109, 'Hardcoded string found')
  - (127, 'Hardcoded string found')
Issues in components/logo/Logo.jsx:
  - (2, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (21, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (32, 'Line exceeds 80 characters')
  - (35, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
Issues in package.json:
  - (3, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
Issues in pages/[piggybankName].js:
  - (2, 'Line exceeds 80 characters')
  - (5, 'TODO found')
  - (12, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (38, 'TODO found')
Issues in pages/_document.jsx:
  - (14, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
Issues in pages/api/createPiggybank.js:
  - (3, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
Issues in pages/test.js:
  - (2, 'Line exceeds 80 characters')
Issues in server/middleware/requireFirebaseToken.js:
  - (1, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (13, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
