### ISSUE TITLE
Issue-handle whats displayed if piggybank not set up yet, move theme color location

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#72]
Automated Review Comments
Issues in components/PublicPiggybankPage/EditPiggybankModal/EditPiggybankModal.jsx:
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
Issues in components/PublicPiggybankPage/ManagePiggybankBar/ManagePiggybankBar.jsx:
  - (8, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/PublicPiggybankPage.jsx:
  - (4, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (25, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (36, 'Line exceeds 80 characters')
  - (36, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (43, 'Line exceeds 80 characters')
  - (52, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (75, 'Line exceeds 80 characters')
  - (75, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (78, 'Line exceeds 80 characters')
  - (79, 'Hardcoded string found')
  - (82, 'Line exceeds 80 characters')
  - (91, 'Hardcoded string found')
  - (92, 'Line exceeds 80 characters')
  - (103, 'Line exceeds 80 characters')
  - (103, 'Hardcoded string found')
  - (104, 'Line exceeds 80 characters')
  - (106, 'Line exceeds 80 characters')
  - (106, 'Hardcoded string found')
  - (113, 'Line exceeds 80 characters')
  - (113, 'Hardcoded string found')
  - (114, 'Line exceeds 80 characters')
  - (116, 'Line exceeds 80 characters')
  - (116, 'Hardcoded string found')
  - (117, 'Line exceeds 80 characters')
  - (124, 'Line exceeds 80 characters')
  - (124, 'Hardcoded string found')
  - (137, 'Hardcoded string found')
Issues in components/theme.js:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (17, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
