### ISSUE TITLE
Issue-Merge pull request #8 from markjackson02/piggybank-setup

handle whats displayed if piggybank not set up yet, move theme color …

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#74]
Automated Review Comments

**Comment by satokihanada** [comment]
I got it.

**Comment by SoldierFace** [comment]
install this

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ

you may need to install the c compiler
