### ISSUE TITLE
Issue-update logo, add facebook auth (#1)

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#8]
Automated Review Comments
Issues in components/FirebaseAuth.js:
  - (17, 'Hardcoded string found')
Issues in components/logo/Logo.jsx:
  - (2, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (22, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
