### ISSUE TITLE
Issue-wip...

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#90]
Automated Review Comments
Issues in components/LandingPage/LandingPage.jsx:
  - (2, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (40, 'Line exceeds 80 characters')
  - (44, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (47, 'Line exceeds 80 characters')
  - (47, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (50, 'Line exceeds 80 characters')
  - (50, 'Hardcoded string found')
  - (51, 'Line exceeds 80 characters')
  - (51, 'Hardcoded string found')
  - (52, 'Line exceeds 80 characters')
  - (52, 'Hardcoded string found')
  - (53, 'Line exceeds 80 characters')
  - (53, 'Hardcoded string found')
  - (54, 'Line exceeds 80 characters')
  - (54, 'Hardcoded string found')
  - (55, 'Line exceeds 80 characters')
  - (55, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (64, 'Line exceeds 80 characters')
  - (64, 'Hardcoded string found')
  - (65, 'Line exceeds 80 characters')
  - (65, 'Hardcoded string found')
  - (66, 'Line exceeds 80 characters')
  - (66, 'Hardcoded string found')
  - (67, 'Line exceeds 80 characters')
  - (67, 'Hardcoded string found')
  - (68, 'Line exceeds 80 characters')
  - (68, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (73, 'Line exceeds 80 characters')
  - (73, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/EditPiggybankModal/EditPiggybankModal.jsx:
  - (9, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (52, 'Line exceeds 80 characters')
  - (53, 'Line exceeds 80 characters')
  - (55, 'Hardcoded string found')
  - (56, 'Line exceeds 80 characters')
  - (59, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (80, 'Line exceeds 80 characters')
  - (80, 'Hardcoded string found')
  - (82, 'Line exceeds 80 characters')
  - (82, 'Hardcoded string found')
  - (83, 'Line exceeds 80 characters')
  - (83, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (95, 'Line exceeds 80 characters')
  - (96, 'Line exceeds 80 characters')
  - (97, 'Line exceeds 80 characters')
  - (101, 'Line exceeds 80 characters')
  - (106, 'Line exceeds 80 characters')
  - (106, 'Hardcoded string found')
  - (113, 'Line exceeds 80 characters')
  - (115, 'Line exceeds 80 characters')
  - (121, 'Line exceeds 80 characters')
  - (124, 'Line exceeds 80 characters')
  - (126, 'Line exceeds 80 characters')
  - (128, 'Line exceeds 80 characters')
  - (132, 'Line exceeds 80 characters')
  - (132, 'Hardcoded string found')
  - (151, 'Line exceeds 80 characters')
  - (161, 'TODO found')
  - (165, 'Hardcoded string found')
  - (169, 'Hardcoded string found')
  - (171, 'Hardcoded string found')
  - (185, 'Line exceeds 80 characters')
  - (195, 'TODO found')
  - (199, 'Hardcoded string found')
  - (202, 'Hardcoded string found')
  - (204, 'Hardcoded string found')
  - (216, 'Hardcoded string found')
  - (217, 'Line exceeds 80 characters')
  - (219, 'Hardcoded string found')
  - (230, 'Hardcoded string found')
  - (239, 'Hardcoded string found')
  - (240, 'Line exceeds 80 characters')
  - (243, 'Hardcoded string found')
  - (254, 'Hardcoded string found')
  - (277, 'Hardcoded string found')
  - (293, 'Hardcoded string found')
  - (302, 'Hardcoded string found')
  - (311, 'Hardcoded string found')
  - (312, 'Hardcoded string found')
  - (313, 'Hardcoded string found')
  - (328, 'Hardcoded string found')
  - (331, 'Hardcoded string found')
  - (332, 'Hardcoded string found')
  - (333, 'Hardcoded string found')
  - (343, 'Hardcoded string found')
  - (346, 'Hardcoded string found')
  - (360, 'Hardcoded string found')
  - (363, 'Hardcoded string found')
  - (371, 'Line exceeds 80 characters')
  - (371, 'Hardcoded string found')
  - (373, 'Hardcoded string found')
  - (374, 'Hardcoded string found')
  - (391, 'Hardcoded string found')
  - (393, 'Hardcoded string found')
  - (394, 'Hardcoded string found')
  - (398, 'Hardcoded string found')
  - (399, 'Hardcoded string found')
  - (401, 'Hardcoded string found')
  - (408, 'Hardcoded string found')
  - (409, 'Hardcoded string found')
  - (411, 'Hardcoded string found')
  - (418, 'Hardcoded string found')
  - (419, 'Hardcoded string found')
  - (435, 'Hardcoded string found')
  - (437, 'Hardcoded string found')
  - (443, 'Hardcoded string found')
  - (445, 'Hardcoded string found')
  - (453, 'Hardcoded string found')
  - (455, 'Hardcoded string found')
Issues in components/PublicPiggybankPage/ManagePiggybankBar/ManagePiggybankBar.jsx:
  - (2, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
Issues in components/PublicPiggybankPage/PublicPiggybankPage.jsx:
  - (1, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (25, 'TODO found')
  - (25, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (30, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')
  - (43, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (73, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
Issues in pages/[piggybankName].js:
  - (9, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'TODO found')
Issues in src/paymentMethods.jsx:
  - (2, 'TODO found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (24, 'Line exceeds 80 characters')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (33, 'Line exceeds 80 characters')
  - (39, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (44, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (55, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (60, 'Line exceeds 80 characters')
  - (63, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (67, 'Line exceeds 80 characters')
  - (72, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (76, 'Line exceeds 80 characters')
  - (82, 'Hardcoded string found')
  - (83, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (86, 'Line exceeds 80 characters')
  - (91, 'Hardcoded string found')
  - (92, 'Hardcoded string found')
  - (95, 'Line exceeds 80 characters')
  - (96, 'Line exceeds 80 characters')
  - (97, 'Line exceeds 80 characters')
  - (98, 'Line exceeds 80 characters')
  - (99, 'Line exceeds 80 characters')
  - (100, 'Line exceeds 80 characters')
  - (106, 'Hardcoded string found')
  - (107, 'Hardcoded string found')
  - (108, 'Hardcoded string found')
  - (110, 'Hardcoded string found')
  - (111, 'Line exceeds 80 characters')
  - (117, 'Hardcoded string found')
  - (118, 'Hardcoded string found')
  - (119, 'Hardcoded string found')
  - (121, 'Line exceeds 80 characters')
  - (126, 'Hardcoded string found')
  - (127, 'Hardcoded string found')
  - (128, 'Hardcoded string found')
  - (131, 'Line exceeds 80 characters')
  - (137, 'Hardcoded string found')
  - (138, 'Hardcoded string found')
  - (139, 'Hardcoded string found')
  - (141, 'Line exceeds 80 characters')
  - (145, 'Hardcoded string found')
  - (146, 'Hardcoded string found')
  - (147, 'Hardcoded string found')
  - (149, 'Line exceeds 80 characters')
  - (153, 'Hardcoded string found')
  - (154, 'Hardcoded string found')
  - (155, 'Hardcoded string found')
  - (157, 'Line exceeds 80 characters')
  - (161, 'Hardcoded string found')
  - (162, 'Hardcoded string found')
  - (163, 'Hardcoded string found')
  - (165, 'Line exceeds 80 characters')
  - (169, 'Hardcoded string found')
  - (170, 'Hardcoded string found')
  - (171, 'Hardcoded string found')
  - (177, 'Hardcoded string found')
  - (178, 'Hardcoded string found')
  - (179, 'Hardcoded string found')
  - (185, 'Hardcoded string found')
  - (186, 'Hardcoded string found')
  - (187, 'Hardcoded string found')
  - (193, 'Hardcoded string found')
  - (194, 'Hardcoded string found')
  - (195, 'Hardcoded string found')
  - (197, 'Line exceeds 80 characters')
  - (201, 'Hardcoded string found')
  - (202, 'Hardcoded string found')
  - (203, 'Hardcoded string found')
  - (206, 'Line exceeds 80 characters')
  - (209, 'Hardcoded string found')
  - (210, 'Hardcoded string found')
  - (211, 'Hardcoded string found')
  - (213, 'Hardcoded string found')
  - (214, 'Line exceeds 80 characters')
  - (217, 'Hardcoded string found')
  - (218, 'Hardcoded string found')
  - (219, 'Hardcoded string found')
  - (221, 'Line exceeds 80 characters')
  - (225, 'Hardcoded string found')
  - (226, 'Hardcoded string found')
  - (227, 'Hardcoded string found')
  - (230, 'Line exceeds 80 characters')
  - (230, 'Hardcoded string found')
  - (231, 'Line exceeds 80 characters')
  - (235, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
