### ISSUE TITLE
Issue-fix preferred checkbox

### ISSUE THREAD

**Issue by lind0118** [lind0118/coindrop#98]
Automated Review Comments
Issues in components/PublicPiggybankPage/EditPiggybankModal/PaymentMethodsInput.jsx:
  - (1, 'Line exceeds 80 characters')
  - (3, 'Line exceeds 80 characters')
  - (4, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
